# Load plugins as `plugins` instead of `require`
plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

# Fix namespace issues
Style/SafeNavigation:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120 # Adjust as per your preference

  Rails:
    Enabled: true

# Configure specific cops for the plugins (enable or adjust as needed)


