services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nativeAzalea2025!
      MYSQL_DATABASE: mrdbid_development
      MYSQL_USER: mrdbid_user
      MYSQL_PASSWORD: uR!TxC4avEWp
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle # Optional, persistent gems
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://mrdbid_user:uR!TxC4avEWp@db:3306/mrdbid_development
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      OTP_SECRET_ENCRYPTION_KEY: ${OTP_SECRET_ENCRYPTION_KEY}
      APP_HOST: ${APP_HOST:-localhost:3000}
    depends_on:
      - db

volumes:
  db-data:
  bundle_data:
