services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mrdbid_production}
      MYSQL_USER: ${MYSQL_USER:-mrdbid_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    # Don't expose port externally in production for security
    # ports:
    #   - "3306:3306"

  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - ./public:/app/public
      - ./log:/app/log
      - ./tmp:/app/tmp
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://${MYSQL_USER:-mrdbid_user}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE:-mrdbid_production}
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      OTP_SECRET_ENCRYPTION_KEY: ${OTP_SECRET_ENCRYPTION_KEY}
      APP_HOST: ${APP_HOST}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db-data:
  bundle_data:

networks:
  app-network:
    driver: bridge
