INSERT INTO `lookup_items` ( mr_character_id, name, description, comments, data_source_id, created_at, updated_at) VALUES  -- refer to mr_characters table
(2, 'None',     '','',5, now(), now() ),                      -- 2 abundance
(2, 'Low',      '','',5, now(), now() ),
(2, 'Moderate', '','',5, now(), now() ),
(2, 'High',     '','',5, now(), now() ),
(3,'Button','very young','',1, now(), now() ),                 -- 3 mushroom_age
(3,'Young','','',1, now(), now() ),
(3,'Mature','','',1, now(), now() ),
(3,'Past Prime','','',1, now(), now() ),
(4,'None','','',5, now(), now() ),                              -- 4 odor
(4,'Fruity','','',5, now(), now() ),
(4,'Lemony','','',5, now(), now() ),
(4,'Anise (licorice)','','',5, now(), now() ),
(4,'Farinaceous (like fresh meal)','','',5, now(), now() ),
(4,'Pungent','','',5, now(), now() ),
(4,'Nauseous','','',5, now(), now() ),
(4,'Nitrous','','',5, now(), now() ),
(4,'Earthy','','',5, now(), now() ),
(4,'Spermatic','','',5, now(), now() ),
(4,'Garlic','','',4, now(), now() ),
(4,'Maraschino cherries','','',4, now(), now() ),
(4,'Sewer gas','','',4, now(), now() ),
(4,'spicy - red hots - dirty socks','','',4, now(), now() ),
(5,'None','','',5, now(), now() ),                                 -- 5 taste
(5,'Mild','','',5, now(), now() ),
(5,'Bitter','','',5, now(), now() ),
(5,'Acrid (= puckery? astringent)/Peppery','','',5, now(), now() ),
(5,'Agreeable','','',5, now(), now() ),
(5,'Farinaceous (like fresh meal)','','',5, now(), now() ),
(6,'Not Toxic','','',2, now(), now() ),                              -- 6 toxic
(6,'Toxic','','',2, now(), now() ),
(7,'Single, solitary','','',5, now(), now() ),                       -- 7 habit
(7,'Scattered (1-2 feet apart)','','',5, now(), now() ),
(7,'Gregarious (growing in a group)','','',5, now(), now() ),
(7,'Caespitose (clustered, not joined)','','',5, now(), now() ),
(7,'Connate (fused at base)','','',5, now(), now() ),
(7,'Imbricate (overlapping)','','',5, now(), now() ),
(7,'In troops or rings','','',5, now(), now() ),
(10,'Convex','evenly rounded','',5, now(), now() ),                               -- 10 pileus_shape
(10, 'Convex','evenly rounded','',5, now(), now() ),
(10,'ovoid','egg','',5, now(), now() ),
(10,'conic','cone','',5, now(), now() ),
(10,'campanulate','bell-shaped.','vv',5, now(), now() ),
(10,'parabolic','half-egg','',5, now(), now() ),
(10,'pulvinate','cushion','',5, now(), now() ),
(10,'cylindric','bullet','',5, now(), now() ),
(10,'plane','flat','',5, now(), now() ),
(10,'conchate','sea-shell','',5, now(), now() ),
(10,'umbonate','w/bump','',5, now(), now() ),
(10,'cuspidate','Umbonate with a pointy conical apex; Witch-hat shaped. also known as eye-tooth.','',5, now(), now() ),
(10,'papillate','w/nipple','',5, now(), now() ),
(10,'depressed','Saucer-shaped; The center is lower than the cap margin.','',5, now(), now() ),
(10,'umbilicate','a navel-like depression in the center.','',5, now(), now() ),
(10,'infundibuliform','funnel-shaped','',5, now(), now() ),
(11,'Petaloid','petal','',5, now(), now() ),                                     -- 11 pileus_shape_top_view
(11,'Spathulate','spatula','',5, now(), now() ),
(11,'Dimidiate','1/2 circle','',5, now(), now() ),
(11,'Flabelliform','fan-shaped','',5, now(), now() ),
(20,'dry: Dull','','',5, now(), now() ),                                          -- 20 pileus_surface_dryness
(20,'dry:  Silky','','',5, now(), now() ),
(20,'Moist:  lubricous/greasy','','',5, now(), now() ),
(20,'Moist: Glutinous (slimy)','','',5, now(), now() ),
(20,'dry: Shiny','','',5, now(), now() ),
(21,'Smooth','No defining features found on the surface.','',7, now(), now() ),                             -- 21 pileus_surface_texture
(21,'Uneven','A bumpy surface.','',7, now(), now() ),
(21,'Rugose','A wrinkled or rough surface.','',7, now(), now() ),
(21,'Rugulose','A slightly wrinkled surface.','',7, now(), now() ),
(21,'Rivulose','A thinly wrinkled surface of branching wavy or crooked lines.','',7, now(), now() ),
(21,'Scrobiculate','A pitted or furrowed surface.','',7, now(), now() ),
(21,'Warty','Remnants of the universal veil remain on the surface in small patches.','',7, now(), now() ),
(21,'Virgate','A streaked surface.','',7, now(), now() ),
(21,'Hygrophanous','A surface that is transparent when wet and opaque when dry.','',7, now(), now() ),
(21,'Sericeous','A silky surface.','',7, now(), now() ),
(21,'Fibrillose','A surface covered in thread-like filaments.','',7, now(), now() ),
(21,'Squamose','A surface covered with scales.','',7, now(), now() ),
(21,'Squarrose','A ragged surface covered with small scales.','',7, now(), now() ),
(21,'Pruinose','A surface covered with a white powdery frostlike substance.','',7, now(), now() ),
(21,'Pulverulent','A surface covered with fine dust or powder.','',7, now(), now() ),
(21,'Granulose','A surface covered in salt-like granulates.','',7, now(), now() ),
(21,'Furfuraceous','A surface covered in flaky bran-like particles; dandruff-like.','',7, now(), now() ),
(21,'Zonate','A surface containing zones or bands that are distinguished by texture or color.','',7, now(), now() ),
(21,'Areolate','A cracked surface resembling dried-mud or paint.','',7, now(), now() ),
(21,'Rimose','A surface covered in cracks and crevices.','',7, now(), now() ),
(21,'Laccate','A waxy or lacquered surface texture.','',7, now(), now() ),
(21, 'Viscid -','A sticky glue-like surface texture.','',7, now(), now() ),
(21,'Glutinous','A slimy surface.','',7, now(), now() ),
(21,'Glabrous - Hairy','Hairy - a bald surface.','',7, now(), now() ),
(21,'Velvety - Hairy','Hairy - A surface covered with very fine and soft hairs.','',7, now(), now() ),
(21,'Pubescent - Hairy','Hairy - A surface cover with fuzz or fine hairs.','',7, now(), now() ),
(21,'Canescent - Hairy','Hairy - A surface covered in dense white or gray down-like hairs. Giving a frosted appearance.','',7, now(), now() ),
(21,'Floccose - Hairy','Hairy - A surface covered in Wooly or cotton-like hairs.','',7, now(), now() ),
(21,'Tomentose - Hairy','Hairy - A surface covered densely with matted hairs.','',7, now(), now() ),
(21,'Hispid - Hairy','Hairy - A surface covered with straight bristle-like hairs.','',7, now(), now() ),
(21,'Hirsute - Hairy','Hairy - A surface covered with slightly stiff and shaggy hairs.','',7, now(), now() ),
(21,'Villose - Hairy','Hairy - A surface covered with long soft hairs.','',7, now(), now() ),
(21,'Strigose - Hairy','Hairy - A surface covered with long bristle-like hairs.','',7, now(), now() ),
(22,'Straight','The margins remain uniform and do not curve.','edited 3-8-2023',7, now(), now() ),                                         -- 22 pileus_margin_shape
(22,'Decurved','The margins curve slightly downwards.','',7, now(), now() ),
(22,'Incurved','The margins curve down and inwards.','',7, now(), now() ),
(22,'Involute','The margins curve downwards and roll inwards. Also known as inrolled.','',7, now(), now() ),
(22,'Arched','The margins curve upwards between the edge and stipe (stem).','',7, now(), now() ),
(22,'Uplifted','The margins curve upwards. Also known as elevated.','',7, now(), now() ),
(22,'Revolute','The margins curve inwards and also rolled back..','',7, now(), now() ),
(22,'Exceeding','The margins extend past the gills.','',7, now(), now() ),
(23,'Entire','There is a smooth transition from the top of the cap to its underside. No irregular attributes should be present on the edges. Also referred to as Smooth, Even, Seamless, Flush, or Regular.','',7, now(), now() ),   -- 23 pileus_margin_type
(23,'Appendiculate','Remnants of a partial veil hang from the edge of the cap.','',7, now(), now() ),
(23,'Striate','Fine and narrow stripes run parallel on the cap margins. The lines will often coincide with the gills underneath the cap. In some cases, the lines are only visible when the cap is wet. Also referred to as striped, furrowed, streaked, ribbed, lined,','',7, now(), now() ),
(23,'Sulcate','Narrow parallel grooves that line the margins of the cap. Sulcate margins are more defined than striate but less ridged than plicated. Also referred to as plicate-striate.','',7, now(), now() ),
(23,'Plicate','Parallel pleated margins. They are best described as fan-like or umbrella-like as if the surface of the cap were folded. Plicate margins are more defined and ridged than Striate or Sulcate. Also referred to as pleated or ridged.','',7, now(), now() ),
(23,'Eroded','Deteriorated, gnawed, or eaten away. The disfigured margins are usually found in older specimens and are the result of insects or deliquescence (common with Ink Caps). Also referred to as gnawed or ragged.','',7, now(), now() ),
(23,'Split','The edges of the cap are split apart or full of large crevices. Also referred to as cracked or rimose.','',7, now(), now() ),
(23,'Lacerate','Many tears mark the edge of the cap. Similar to split margins, however, the cuts are smaller and more frequent. Also referred to as torn.','',7, now(), now() ),
(23,'Undulating - Hairy','Hairy - The edges of the cap form a wave-like pattern as they rise and fall. Also referred to as wavy irregular or festoony.','',7, now(), now() ),
(23,'Crenate - Hairy','Hairy - Semi-circle notches or round-toothed edges that are more blunted than serrate margins. Also referred to as scalloped.','',7, now(), now() ),
(23,'Serrate - Hairy','Hairy - The edges of the cap appear jagged and saw-toothed. More pronounced than crenate margins.','',7, now(), now() ),
(30,'Soft','','',5, now(), now() ),                                               -- 30 pileus_context_flesh_texture
(30,'Spongy','','',5, now(), now() ),
(30,'Firm','','',5, now(), now() ),
(30,'Compact','','',5, now(), now() ),
(30,'Rigid','','',5, now(), now() ),
(30,'Brittle','','',5, now(), now() ),
(30,'Corky','','',5, now(), now() ),
(30,'Other','','',5, now(), now() ),
(35,'Free - remote','','',5, now(), now() ),                                  -- 35 lamella_attachment
(35,'Free - close','','',5, now(), now() ),
(35,'Adnate - horizontal','','',5, now(), now() ),
(35,'Adnate - ascending','','',5, now(), now() ),
(35,'Adnexed (almost free)','','',5, now(), now() ),
(35,'Sinuate','','',5, now(), now() ),
(35,'Emarginate (notched)','','',5, now(), now() ),
(35,'Decurrent - long','','',5, now(), now() ),
(35,'Decurrent - short','','',5, now(), now() ),
(35,'Seceding (breaking away)','','',5, now(), now() ),
(35,'Uncinate (w/decurrent tooth)','','',5, now(), now() ),
(35,'Collared','Gills are attached to a collar or ring that encircles the stipe.','',7, now(), now() ),
(36,'Broad','','',5, now(), now() ),                     -- 36 lamella_breadth
(36,'Free - close','','',5, now(), now() ),
(36,'Ventricose','','',5, now(), now() ),
(37,'Average','','',5, now(), now() ),      -- 37 lamella_thickness
(37,'Thick','','',5, now(), now() ),
(37,'Tapering','','',5, now(), now() ),
(38,'Crowded','The Gills are tightly close together.','',7, now(), now() ),   -- 38 lamella_spacing
(38,'Close','The Gills are close together.','',7, now(), now() ),
(38,'Subdistant','The gills are spaced apart.','',7, now(), now() ),
(38,'Distant','The gills are widely spaced apart.','',7, now(), now() ),
(41,'Even - entire','','',5, now(), now() ),   -- 41 lamella_edge
(41,'Serrate','','',5, now(), now() ),
(41,'Serrulate','','',5, now(), now() ),
(41,'Eroded (\"gnawed\")','','',5, now(), now() ),
(41,'Fimbriate (fringed)','','',5, now(), now() ),
(41,'Marginate (diff. color)','','',5, now(), now() ),
(41,'Crenate (scalloped)','','',5, now(), now() ),
(41,'Acute','','',5, now(), now() ),
(41,'Obtuse (blunt)','','',5, now(), now() ),
(41,'Crisped (crinkled)','','',5, now(), now() ),
(41,'lamella_misc_waxy_y_n','','',4, now(), now() ),
(41,'lamella_misc_arid_dry_y_n','','',4, now(), now() ),
(41,'lamella_misc_deliquescent_y_n','','',4, now(), now() ),
(45,'Central','','',5, now(), now() ),                            -- 45 stipe location
(45,'Eccentric - off-center','','',5, now(), now() ),
(45,'Lateral - attached at margin','','',5, now(), now() ),
(45,'Sessile - missing','','',5, now(), now() ),
(50,'Terete (round)','','',5, now(), now() ),                  -- 50 stipe shape
(50,'Compressed (flattened)','','',5, now(), now() ),
(50,'Equal','','',5, now(), now() ),
(50,'Clavate (club)','','',5, now(), now() ),
(50,'Radicating (w/\"root\")','','',5, now(), now() ),
(50,'Flexous','','',5, now(), now() ),
(50,'Ventricose Fusiform','','',5, now(), now() ),
(50,'Tapering','','',5, now(), now() ),
(50,'Abruptly bulbous','','',5, now(), now() ),
(50,'Rounded','','',5, now(), now() ),
(50,'Oblique (angle)','','',5, now(), now() ),
(50,'Marginate','','',5, now(), now() ),
(58,'Smooth','No defining features found on the surface.','',7, now(), now() ),   -- 58 stipe_surface
(58,'Uneven','A bumpy surface.','',7, now(), now() ),
(58,'Rugose','A wrinkled or rough surface.','',7, now(), now() ),
(58,'Rugulose','A slightly wrinkled surface.','',7, now(), now() ),
(58,'Rivulose','A thinly wrinkled surface of branching wavy or crooked lines.','',7, now(), now() ),
(58,'Scrobiculate','A pitted or furrowed surface.','',7, now(), now() ),
(58,'Warty','Remnants of the universal veil remain on the surface in small patches.','',7, now(), now() ),
(58,'Virgate','A streaked surface.','',7, now(), now() ),
(58,'Hygrophanous','A surface that is transparent when wet and opaque when dry.','',7, now(), now() ),
(58,'Sericeous','A silky surface.','',7, now(), now() ),
(58,'Fibrillose','A surface covered in thread-like filaments.','',7, now(), now() ),
(58,'Squamose','A surface covered with scales.','',7, now(), now() ),
(58,'Squarrose','A ragged surface covered with small scales.','',7, now(), now() ),
(58,'Pruinose','A surface covered with a white powdery frostlike substance.','',7, now(), now() ),
(58,'Pulverulent','A surface covered with fine dust or powder.','',7, now(), now() ),
(58,'Granulose','A surface covered in salt-like granulates.','',7, now(), now() ),
(58,'Furfuraceous','A surface covered in flaky bran-like particles; dandruff-like.','',7, now(), now() ),
(58,'Zonate','A surface containing zones or bands that are distinguished by texture or color.','',7, now(), now() ),
(58,'Areolate','A cracked surface resembling dried-mud or paint.','',7, now(), now() ),
(58,'Rimose','A surface covered in cracks and crevices.','',7, now(), now() ),
(58,'Laccate','A waxy or lacquered surface texture.','',7, now(), now() ),
(58, 'Viscid -','A sticky glue-like surface texture.','',7, now(), now() ),
(58,'Glutinous','A slimy surface.','',7, now(), now() ),
(58,'Glabrous - Hairy','Hairy - a bald surface.','',7, now(), now() ),
(58,'Velvety - Hairy','Hairy - A surface covered with very fine and soft hairs.','',7, now(), now() ),
(58,'Pubescent - Hairy','Hairy - A surface cover with fuzz or fine hairs.','',7, now(), now() ),
(58,'Canescent - Hairy','Hairy - A surface covered in dense white or gray down-like hairs. Giving a frosted appearance.','',7, now(), now() ),
(58,'Floccose - Hairy','Hairy - A surface covered in Wooly or cotton-like hairs.','',7, now(), now() ),
(58,'Tomentose - Hairy','Hairy - A surface covered densely with matted hairs.','',7, now(), now() ),
(58,'Hispid - Hairy','Hairy - A surface covered with straight bristle-like hairs.','',7, now(), now() ),
(58,'Hirsute - Hairy','Hairy - A surface covered with slightly stiff and shaggy hairs.','',7, now(), now() ),
(58,'Villose - Hairy','Hairy - A surface covered with long soft hairs.','',7, now(), now() ),
(58,'Strigose - Hairy','Hairy - A surface covered with long bristle-like hairs.','',7, now(), now() ),
(58,'Banded','','',5, now(), now() ),
(58,'Peronate','','',5, now(), now() ),
(58,'Fibrous','','',5, now(), now() ),
(58,'Lacunose (w/dp.grooves)','','',5, now(), now() ),
(58,'Longitudinally striate','','',5, now(), now() ),
(58,'Ribbed/Costate','','',5, now(), now() ),
(58,'Scabrous (scabby)','','',5, now(), now() ),
(58,'Punctuate (w/small dots)','','',5, now(), now() ),
(58,'Glanular-dotted (w/dark sticky dots)','','',5, now(), now() ),
(58,'Reticulate (fishnet)','','',5, now(), now() ),
(59,'Fragile','','',5, now(), now() ),                              -- 59 stipe_texture
(59,'Pliable','','',5, now(), now() ),
(59,'Chalky','','',5, now(), now() ),
(59,'Rigid','','',5, now(), now() ),
(59,'Fibrous (Fleshy-Fibrous)','usually rather thick, and when broken in two, leaves a ragged edge.','',5, now(), now() ),
(59,'Cartilaginous','Common stipe, usually thin and breaks with a firm split when bent in two, similar to cartilage.','',13, now(), now() ),
(59,'Firm','','',5, now(), now() ),
(59,'Woody','','',13, now(), now() ),
(59,'Corky','','',13, now(), now() ),
(59,'Leathery (coriaceous)','','',13, now(), now() ),
(59,'Chalky','feels and breaks like chalk in hand. When crushed, it breaks up into powder or chunks.','',13, now(), now() ),
(59,'Breaking with a snap','','',5, now(), now() ),
(60,  'Solid',             '','', 5, now(), now() ),            -- 60 stipe_interior
(60,  'Hollow - fistulose','','', 5, now(), now() ),
(60,  'Tubular',           '','', 5, now(), now() ),
(60,  'Cavernous',         '','', 5, now(), now() ),
(60,  'Stuffed with pith', '','', 5, now(), now() ),
(61,'None','Does not have annulus ring','',5, now(), now() ),   -- 61 partial_inner_veil_annular_ring_position
(61,'Superior','Near the cap','',5, now(), now() ),
(61,'Apical','upper half','',5, now(), now() ),
(61,'Median','in the middle','',5, now(), now() ),
(61,'Inferior','Lower half','',5, now(), now() ),
(61,'Basal','Near the base','',5, now(), now() ),
(64,'Membranous (skin-like)','','',5, now(), now() ),   -- 64 partial_inner_veil_texture
(64,'Cortinate (cobwebby)','','',5, now(), now() ),
(64,'Fibillose (thready)','','',5, now(), now() ),
(64,'Gelatinous (slimy)','','',5, now(), now() ),
(65,'Disappearing - Evanescent','can only be detected in button stage','',4, now(), now() ),  -- 65 partial_inner_veil_fate
(65,'Persistent','leaving remnants on cap','',4, now(), now() ),
(67,'Two Rings (from 2 veils)','','',5, now(), now() ),  -- 67  partial_inner_veil_appearance
(67,'Doubly-flared Ring','','',5, now(), now() ),
(67,'\"Cogwheel\" Stellate','','',5, now(), now() ),
(67,'Floccose (downy tuffs)','','',5, now(), now() ),
(67,'Cortinate PV & Fibrillose Annular Zone','','',5, now(), now() ),
(67,'Single Ring thick on edge','','',5, now(), now() ),
(67,'Pendant (hanging)','','',5, now(), now() ),
(67,'Subperonate','','',5, now(), now() ),
(67,'Peronate (w/\"boot\")','','',5, now(), now() ),
(70,'Napiform (turnip)','','',5, now(), now() ),                         -- 70 bulb_type
(70,'Saccate','','',5, now(), now() ),
(70,'Sheathing','','',5, now(), now() ),
(70,'Collar','','',5, now(), now() ),
(70,'Granular','','',5, now(), now() ),
(70,'Concentric rings or scales','','',5, now(), now() ),
(70,'Friable, disappearing','','',5, now(), now() ),
(70,'Fusiform','','',5, now(), now() ),
(70,'Marginate-depressed','','',5, now(), now() ),
(70,'Cleft','','',5, now(), now() ),
(76,'Terrestrial (on soil - bare )','','',5, now(), now() ),           -- 76 habitat
(76,'Terrestrial (on soil - burned )','','',5, now(), now() ),
(76,'Terrestrial (on soil - disturbed )','','',5, now(), now() ),
(76,'Lignicolous (on wood) - what kind of tree?','','',5, now(), now() ),
(76,'Humicolous (on humus, duff) - conifer, other?','','',5, now(), now() ),
(76,'Coprophious (on dung) what kind?','','',5, now(), now() ),
(76,'In grassy area - lawn, pasture, etc?','','',5, now(), now() ),
(76,'In forest - conifer, hardwood, mixed?','','',5, now(), now() ),
(76,'fungicolous','mushroom mycelia grow in other mushrooms','p 7, How to Identify Mushrooms to Genus I: Macroscopic Features - David L. Largent',13,'2023-03-16 21:46:17','2023-03-16 21:46:17'),
(77,'Unknown','','',1, now(), now() ),                                  -- 77 soil_type
(77,'Loam','','',1, now(), now() ),
(83,'Ammonia (NH4OH, Ammonium Hydroxide)','','',8, now(), now() ),  -- 83 chem_reaction
(83,'KOH (Potassium Hydroxide) - 3%','','',8, now(), now() ),
(99,'Superior','Near the cap','',7, now(), now() ),      --  99 annulus_position
(99,'Apical','upper half', '',   7, now(), now() ),
(99,'Median','in the middle','', 7, now(), now() ),
(99,'Inferior','Lower half','',  7, now(), now() ),
(99,'Basal','Near the base','',  7, now(), now() ),
(100,'Observation Only - No specimen collected','','',2, now(), now() ),              -- 100 mushroom_storage_location
(100,'Specimen Collector','This is you, if you collected this specimen','',2, now(), now() ),
(100,'Herbarium','','',2, now(), now() ),
(101, 'USA', 'United States', '',  23, now(), now() ),  -- 101 countries  - states has own table
(101, 'MEX', 'Mexico',        '',  23, now(), now() ),
(101, 'CAN', 'Canada',        '',  23, now(), now() ),
(105,'Lamella - Gills','','',1, now(), now() ),        -- 105 fungus_types
(105,'Pores','','',1, now(), now() ),
(105,'Teeth','','',1, now(), now() ),
(105,'Cups','','',1, now(), now() ),
(105,'Stinkhorn','','',1, now(), now() ),
(106,'Two Rings (from 2 veils)','','',5, now(), now() ),               -- 106 universal_outer_veil_appearances
(106,'Doubly-flared Ring','','',5, now(), now() ),
(106,'\"Cogwheel\" Stellate','','',5, now(), now() ),
(106,'Floccose (downy tuffs)','','',5, now(), now() ),
(106,'Cortinate PV & Fibrillose Annular Zone','','',5, now(), now() ),
(106,'Single Ring thick on edge','','',5, now(), now() ),
(106,'Pendant (hanging)','','',5, now(), now() ),
(106,'Subperonate','','',5, now(), now() ),
(106,'Peronate (w/\"boot\")','','',5, now(), now() ),
(107,'Disappearing','','',5, now(), now() ),                          -- 107 universal_outer_veil_fates
(107,'Leaving fragments on cap','','',5, now(), now() ),
(108,'Membranous (skin-like)','','',5, now(), now() ),                        -- 108  `universal_outer_veil_textures
(108,'Cortinate (cobwebby)','','',5, now(), now() ),
(108,'Fibillose (thready)','','',5, now(), now() ),
(108,'Gelatinous (slimy)','','',5, now(), now() ),
(109,'Flaring','The annulus is flaring upwards.','',7, now(), now() ),                                -- 109  veils
(109,'Pendant','The veil is hanging downward from the stipe.','',7, now(), now() ),
(109,'Double Rings','Two visible veils..','',7, now(), now() ),
(109,'Ring Zone','The stipe is marked with the remnants of the annulus','',7, now(), now() ),
(109,'Cortinate','The partial veil is cobweb-like or tread-like (Fibrillose)..','',7, now(), now() ),
(109,'Stellate','The partial veil resembles a cogwheel.','',7, now(), now() ),
(109,'Floccose','The partial veil is fluffy and down-like.','',7, now(), now() ),
(109,'Peronate','The stipe resembles a sheath-like boot or stocking','',7, now(), now() ),
(110,'epigeous','above-ground ','',2, now(), now() ),                                             -- 110 synonyms
(110,'hypogeous','underground','',2, now(), now() ),
(110,'mushroom','fruiting body of a fungus','',2, now(), now() ),
(110,'basidiocarp','fruiting body','',2, now(), now() ),
(110,'thallus','soma','entire body of fungus',2, now(), now() ),
(110,'sporocarp','fruiting body','',2, now(), now() ),
(110,'pileus','cap','',2, now(), now() ),
(110,'Stipe','Stalk','',2, now(), now() ),
(110,'Gills','Lamellae','',2, now(), now() ),
(110,'Volva','cup','',2, now(), now() ),
(110,'Annulus','ring','',2, now(), now() ),
(110,'cone','conical','',5, now(), now() ),
(110,'conic','conical','',5, now(), now() ),
(110,'disc','center','',5, now(), now() ),
(110,'margin','edge','',5, now(), now() ),
(110,'ring','annulus','',5, now(), now() ),
(110,'stem','stipe','',5, now(), now() ),
(110,'volva','cup','',5, now(), now() ),
(110,'convex','evenly rounded','',1, now(), now() ),
(110,'ovoid','egg','',5, now(), now() ),
(110,'campanulate','bell-shaped','',5, now(), now() ),
(110,'parabolic','half-egg','',5, now(), now() ),
(110,'pulvinate','cushion','',5, now(), now() ),
(110,'cylindric','bullet','',5, now(), now() ),
(110,'plane','flat','',5, now(), now() ),
(112,'Convex','','',44,now(),now() ),     -- 112 pileus_shape_form
(112,'Hemispherical','','',44,now(),now() ),
(112,'Spherical','','',44,now(),now() ),
(112,'Ovoid','','',44,now(),now() ),
(112,'Conical','','',44,now(),now() ),
(112,'Cylindric','','',44,now(),now() ),
(112,'Flat','','',44,now(),now() ),
(112,'Depressed','','',44,now(),now() ),
(112,'Funnel-Shaped','','',44,now(),now() ),
(112,'Companulate','','',44,now(),now() ),
(112,'Cuspidate','','',44,now(),now() ),
(112,'Umbonate','','',44,now(),now() ),
(112,'Papillate','','',44,now(),now() ),
(112,'Umbilicate','','',44,now(),now() ),
(112,'Uplifted','','',44,now(),now() ),
(112,'Parabolic','','',44,now(),now() ),
(112,'Pulvinate','','',44,now(),now() ),
(112,'Plane','','',44,now(),now() ),
(112,'Infundibuliform','','',44,now(),now() ),
(112,'Other','','',44,now(),now() ),
(117,'Dry','','',44,now(),now() ),                      -- 117 pileus_surface_wetness
(117,'Moist','','',44,now(),now() ),
(117,'Glutinous','','',44,now(),now() ),
(117,'Gelatinous','','',44,now(),now() ),
(117,'Viscid','','',44,now(),now() ),
(117,'Subviscid','','',44,now(),now() ),
(117,'Other','','',44,now(),now() ),
(120,'Indented','','',44,now(),now() ),                          -- 120 pileus_center
(120,'Nearly perforated','','',44,now(),now() ),
(120,'Perforated','','',44,now(),now() ),
(121,'Darker','','',44,now(),now() ),                                 -- 121 pileus_central_disc_colored
(121,'Lighter','','',44,now(),now() ),
(124,'Glabrous smooth','','',44,now(),now() ),                      -- 124 pileus_surface_texture
(124,'non-glabrous Downy-Wooly','','',44,now(),now() ),
(124,'non-glabrous Matted-Fibrillose','','',44,now(),now() ),
(124,'non-glabrous Furfuraceous','','',44,now(),now() ),
(124,'non-glabrous Granulose','','',44,now(),now() ),
(124,'non-glabrous Pruinose','','',44,now(),now() ),
(124,'non-glabrous Squamose','','',44,now(),now() ),
(124,'non-glabrous Squamulose','','',44,now(),now() ),
(124,'non-glabrous Scaly','','',44,now(),now() ),
(124,'non-glabrous Hairy','','',44,now(),now() ),
(124,'Shaggy','','',44,now(),now() ),
(124,'Bristled/Bristly','','',44,now(),now() ),
(124,'Strigose','','',44,now(),now() ),
(124,'Warted','','',44,now(),now() ),
(124,'Appressed','','',44,now(),now() ),
(124,'Appressed-Fibrillose','','',44,now(),now() ),
(124,'Tomentose','','',44,now(),now() ),
(124,'Virgate','','',44,now(),now() ),
(124,'Scrobiculate','','',44,now(),now() ),
(124,'Alveolate','','',44,now(),now() ),
(124,'Lacunose','','',44,now(),now() ),
(124,'Lacinate','','',44,now(),now() ),
(124,'Areolate','','',44,now(),now() ),
(124,'Atomate','','',44,now(),now() ),
(124,'Micaceous','','',44,now(),now() ),
(124,'Superficial','','',44,now(),now() ),
(124,'Innate','','',44,now(),now() ),
(124,'Venose','','',44,now(),now() ),
(124,'non-glabrous Other','','',44,now(),now() ),
(143,'Close','','',44,now(),now() ),                                       -- 143 lamellae_distance_spacing
(143,'Crowded','','',44,now(),now() ),
(143,'Distant','','',44,now(),now() ),
(143,'Sub-Distant','','',44,now(),now() ),
(143,'Other','','',44,now(),now() ),
(144,'Average','','',44,now(),now() ),             -- 144 lamellae_thickness
(144,'Thick','','',44,now(),now() ),
(144,'Tapering','','',44,now(),now() ),
(144,'Other','','',44,now(),now() ),
(145,'Narrow','','',44,now(),now() ),              -- 145 lamellae_blade_breadth
(145,'Broad','','',44,now(),now() ),
(145,'Ventricose','','',44,now(),now() ),
(147,'Adnate','','',44,now(),now() ),                                -- 147 lamellae_attachment
(147,'Adnexed','','',44,now(),now() ),
(147,'Sinuate','','',44,now(),now() ),
(147,'Decurrent','','',44,now(),now() ),
(147,'Collared','','',44,now(),now() ),
(147,'Other','','',44,now(),now() ),
(159,'Serrated','','',44,now(),now() ),                   -- 159 lamellae_margins_nuanced_texture_appearance
(159,'Eroded','','',44,now(),now() ),
(159,'Sinuate','','',44,now(),now() ),
(159,'Wrinkled','','',44,now(),now() ),
(159,'Other','','',44,now(),now() ),
(174,'Smooth','','',44,now(),now() ),           -- 174 stipe_surface_texture
(174,'Banded','','',44,now(),now() ),
(174,'Peronate','','',44,now(),now() ),
(174,'Fibrose','','',44,now(),now() ),
(174,'Lacunose','','',44,now(),now() ),
(174,'Longtidunally Striate','','',44,now(),now() ),
(174,'Ribbed [Costate]','','',44,now(),now() ),
(174,'Scabrous','','',44,now(),now() ),
(174,'Pruinose [Powdery]','','',44,now(),now() ),
(174,'Speckled','','',44,now(),now() ),
(174,'Punctate','','',44,now(),now() ),
(174,'Glandular-Dotted','','',44,now(),now() ),
(174,'Reticulate','','',44,now(),now() ),
(174,'Other','','',44,now(),now() ),
(177,'Centrally solid','','',44,now(),now() ),                 -- 177 stipe_interior
(177,'Stuffed (w/hyphae)','','',44,now(),now() ),
(177,'hollow','','',44,now(),now() ),
(177,'Fistulose','','',44,now(),now() ),
(177,'Broadly fistulose','','',44,now(),now() ),
(177,'Partially stuffed/partially hollow','','',44,now(),now() ),
(177,'Chambered','','',44,now(),now() ),
(198,'Flexuose','','',44,now(),now() ),                              -- 198 stipe_form
(198,'Straight','','',44,now(),now() ),
(198,'Extremely flexuose','','',44,now(),now() ),
(198,'Somewhat flexuose','','',44,now(),now() ),
(198,'Consistently Straight','','',44,now(),now() ),
(198,'Other','','',44,now(),now() ),
(234,'On soil','','',44,now(),now() ),                             -- 234 substrata
(234,'Decaying wood','','',44,now(),now() ),
(234,'Humus','','',44,now(),now() ),
(234,'Duff','','',44,now(),now() ),
(234,'Bryophytes','','',44,now(),now() ),
(234,'Dung','','',44,now(),now() ),
(234,'Grass','','',44,now(),now() ),
(234,'Tree Cones','','',44,now(),now() ),
(234,'Tree Needles','','',44,now(),now() ),
(234,'Leaves','','',44,now(),now() ),
(234,'Other','','',44,now(),now() ),
(236,'Saprophytic','','',44,now(),now() ),                         -- 236 nutrition_mode
(236,'Parasitic','','',44,now(),now() ),
(236,'Endophytic','','',44,now(),now() ),
(236,'Ectomycorrhizal','','',44,now(),now() ),
(236,'Symbiotic','','',44,now(),now() ),
(236,'Other','','',44,now(),now() ),
(259,'Fragile','','',44,now(),now() ),                 -- 259 basidiocarps_fragile_normal_tough
(259,'Normal','','',44,now(),now() ),
(259,'Tough','','',44,now(),now() ),
(260,'None','','',44,now(),now() ),    -- 260 handling_specimen_color_change
(260,'Subtle','','',44,now(),now() ),
(260,'Drastic','','',44,now(),now() ),
(316,'Almond-like','','',44,now(),now() ),                              -- 316 aroma
(316,'Bakery-like','','',44,now(),now() ),
(316,'Dark cacao chocolate-like','','',44,now(),now() ),
(316,'Apricot-like','','',44,now(),now() ),
(316,'Frozen orange juice-like','','',44,now(),now() ),
(316,'Normal/common','','',44,now(),now() ),
(316,'Cucumber-like','','',44,now(),now() ),
(316,'Anise-like','','',44,now(),now() ),
(316,'Garlic-like','','',44,now(),now() ),
(316,'Coal-tar-like','','',44,now(),now() ),
(316,'Radish-like','','',44,now(),now() ),
(316,'Cedar-like','','',44,now(),now() ),
(316,'Bleach-like','','',44,now(),now() ),
(316,'Spermatic','','',44,now(),now() ),
(316,'Shrimp-like','','',44,now(),now() ),
(316,'Maraschino-cherry_like','','',44,now(),now() ),
(316,'Acrid','','',44,now(),now() ),
(316,'Other','','',44,now(),now() ),
(319,'Cutis','','',44,now(),now() ),        -- 319 pileus_pileipellis_pattern
(319,'Dry Cutis','','',44,now(),now() ),
(319,'Ixocutis','','',44,now(),now() ),
(319,'Pluristratous Hymeniderm','','',44,now(),now() ),
(319,'Hymeniform','','',44,now(),now() ),
(319,'Trichoderm','','',44,now(),now() ),
(319,'Other','','',44,now(),now() ),
(387,'Parallel','','',44,now(),now() ),                  -- 387 lamellae_lamellae_trama_pattern
(387,'Subregular','','',44,now(),now() ),
(387,'Interwoven','','',44,now(),now() ),
(387,'Divergent [Bilateral]','','',44,now(),now() ),
(387,'Divergent (Bilateral) & Multi-Sized','','',44,now(),now() ),
(387,'Convergent','','',44,now(),now() ),
(387,'Subcellular','','',44,now(),now() );