INSERT INTO `states` VALUES (1,'Alabama','','',1, now(), now() ),
                            (2,'Alaska','','',1, now(), now() ),
                            (3,'Arizona','','',1, now(), now() ),
                            (4,'Arkansas','','',1, now(), now() ),
                            (5,'California','','',1, now(), now() ),
                            (6,'Colorado','','',1, now(), now() ),
                            (7,'Connecticut','','',1, now(), now() ),
                            (8,'Delaware','','',1, now(), now() ),
                            (9,'District of Columbia','','',1, now(), now() ),
                            (10,'Florida','','',1, now(), now() ),
                            (11,'Georgia','','',1, now(), now() ),
                            (12,'Hawaii','','',1, now(), now() ),
                            (13,'Idaho','','',1, now(), now() ),
                            (14,'Illinois','','',1, now(), now() ),
                            (15,'Indiana','','',1, now(), now() ),
                            (16,'Iowa','','',1, now(), now() ),
                            (17,'Kansas','','',1, now(), now() ),
                            (18,'Kentucky','','',1, now(), now() ),
                            (19,'Louisiana','','',1, now(), now() ),
                            (20,'Maine','','',1, now(), now() ),
                            (21,'Maryland','','',1, now(), now() ),
                            (22,'Massachusetts','','',1, now(), now() ),
                            (23,'Michigan','','',1, now(), now() ),
                            (24,'Minnesota','','',1, now(), now() ),
                            (25,'Mississippi','','',1, now(), now() ),
                            (26,'Missouri','','',1, now(), now() ),
                            (27,'Montana','','',1, now(), now() ),
                            (28,'Nebraska','','',1, now(), now() ),
                            (29,'Nevada','','',1, now(), now() ),
                            (30,'New Hampshire','','',1, now(), now() ),
                            (31,'New Jersey','','',1, now(), now() ),
                            (32,'New Mexico','','',1, now(), now() ),
                            (33,'New York','','',1, now(), now() ),
                            (34,'North Carolina','','',1, now(), now() ),
                            (35,'North Dakota','','',1, now(), now() ),
                            (36,'Ohio','','',1, now(), now() ),
                            (37,'Oklahoma','','',1, now(), now() ),
                            (38,'Oregon','','',1, now(), now() ),
                            (39,'Pennsylvania','','',1, now(), now() ),
                            (40,'Rhode Island','','',1, now(), now() ),
                            (41,'South Carolina','','',1, now(), now() ),
                            (42,'South Dakota','','',1, now(), now() ),
                            (43,'Tennessee','','',1, now(), now() ),
                            (44,'Texas','','',1, now(), now() ),
                            (45,'Utah','','',1, now(), now() ),
                            (46,'Vermont','','',1, now(), now() ),
                            (47,'Virginia','','',1, now(), now() ),
                            (48,'Washington','','',1, now(), now() ),
                            (49,'West Virginia','','',1, now(), now() ),
                            (50,'Wisconsin','','',1, now(), now() ),
                            (51,'Wyoming','','',1, now(), now() ),
                            (52,'Alberta','','',3, now(), now() ),
                            (53,'British Columbia','','',3, now(), now() ),
                            (54,'Manitoba','','',3, now(), now() ),
                            (55,'New Brunswick','','',3, now(), now() ),
                            (56,'Newfoundland','','',3, now(), now() ),
                            (57,'Nova Scotia','','',3, now(), now() ),
                            (58,'Northwest Territories','','',3, now(), now() ),
                            (59,'Nunavut','','',3, now(), now() ),
                            (60,'Ontario','','',3, now(), now() ),
                            (61,'Prince Edward Island','','',3, now(), now() ),
                            (62,'Quebec','','',3, now(), now() ),
                            (63,'Saskatchewan','','',3, now(), now() ),
                            (64,'Yukon','','',3, now(), now() ),
                            (65,'Aguascalientes','','',2, now(), now() ),
                            (66,'Baja California','','',2, now(), now() ),
                            (67,'Baja California Sur','','',2, now(), now() ),
                            (68,'Campeche','','',2, now(), now() ),
                            (69,'Chiapas','','',2, now(), now() ),
                            (70,'Chihuahua','','',2, now(), now() ),
                            (71,'Coahuila','','',2, now(), now() ),
                            (72,'Colima','','',2, now(), now() ),
                            (73,'Distrito Federal','','',2, now(), now() ),
                            (74,'Durango','','',2, now(), now() ),
                            (75,'Guanajuato','','',2, now(), now() ),
                            (76,'Guerrero','','',2, now(), now() ),
                            (77,'Hidalgo','','',2, now(), now() ),
                            (78,'Jalisco','','',2, now(), now() ),
                            (79,'Mexico','','',2, now(), now() ),
                            (80,'Michoacan','','',2, now(), now() ),
                            (81,'Morelos','','',2, now(), now() ),
                            (82,'Nayarit','','',2, now(), now() ),
                            (83,'Nuevo Leon','','',2, now(), now() ),
                            (84,'Oaxaca','','',2, now(), now() ),
                            (85,'Puebla','','',2, now(), now() ),
                            (86,'Queretaro','','',2, now(), now() ),
                            (87,'Quintana Roo','','',2, now(), now() ),
                            (88,'San Luis Potosi','','',2, now(), now() ),
                            (89,'Sinaloa','','',2, now(), now() ),
                            (90,'Sonora','','',2, now(), now() ),
                            (91,'Tabasco','','',2, now(), now() ),
                            (92,'Tamaulipas','','',2, now(), now() ),
                            (93,'Tlaxcala','','',2, now(), now() ),
                            (94,'Veracruz','','',2, now(), now() ),
                            (95,'Yucatan','','',2, now(), now() ),
                            (96,'Zacatecas','','',2, now(), now() );