INSERT INTO `abundances` VALUES (99,'Not Entered','','',1, now(), now() ),
                                (100,'None','','',1, now(), now() ),
                                (101,'Low','','',1, now(), now() ),
                                (102,'Moderate','','',1, now(), now() ),
                                (103,'High','','',1, now(), now() );
INSERT INTO `annulus_positions` VALUES (1,'Not Entered','',1,5,  now(), now() ),
                                       (2,'Superior','Near the cap','',7, now(), now() ),
                                       (3,'Apical','upper half','',7, now(), now() ),
                                       (4,'Median','in the middle','',7, now(), now() ),
                                       (5,'Inferior','Lower half','',7, now(), now() ),
                                       (6,'Basal','Near the base','',7, now(), now() );
INSERT INTO `bulb_types` VALUES (1,'Not Entered','','',1, now(), now() ),
                                (2,'Napiform (turnip)','','',5, now(), now() ),
                                (3,'Saccate','','',5, now(), now() ),
                                (4,'Sheathing','','',5, now(), now() ),
                                (5,'Collar','','',5, now(), now() ),
                                (6,'Granular','','',5, now(), now() ),
                                (7,'Concentric rings or scales','','',5, now(), now() ),
                                (8,'Friable, disappearing','','',5, now(), now() ),
                                (9,'Fusiform','','',5, now(), now() ),
                                (10,'Marginate-depressed','','',5, now(), now() ),
                                (11,'Cleft','','',5, now(), now() );
INSERT INTO `pileus_context_flesh_textures` VALUES (1,'Not Entered','','',5, now(), now() ),
                                                (2,'Soft','','',5, now(), now() ),
                                                (3,'Spongy','','',5, now(), now() ),
                                                (4,'Firm','','',5, now(), now() ),
                                                (5,'Compact','','',5, now(), now() ),
                                                (6,'Rigid','','',5, now(), now() ),
                                                (7,'Brittle','','',5, now(), now() ),
                                                (8,'Corky','','',5, now(), now() ),
                                                (9,'Other','','',5, now(), now() );
INSERT INTO `pileus_margin_shapes` VALUES (1,'Not Entered','','',1,'2023-02-21 21:37:26','2023-02-21 21:37:26'),
                                       (2,'Straight','The margins remain uniform and do not curve.','edited 3-8-2023',7, now(), now() ),
                                       (3,'Decurved','The margins curve slightly downwards.','',7, now(), now() ),
                                       (4,'Incurved','The margins curve down and inwards.','',7, now(), now() ),
                                       (5,'Involute','The margins curve downwards and roll inwards. Also known as inrolled.','',7, now(), now() ),
                                       (6,'Arched','The margins curve upwards between the edge and stipe (stem).','',7, now(), now() ),
                                       (7,'Uplifted','The margins curve upwards. Also known as elevated.','',7, now(), now() ),
                                       (8,'Revolute','The margins curve inwards and also rolled back..','',7, now(), now() ),
                                       (9,'Exceeding','The margins extend past the gills.','',7, now(), now() );
INSERT INTO `pileus_margin_types` VALUES (1,'Not Entered','','',1,'2023-02-21 21:37:26','2023-02-21 21:37:26'),
                                      (2,'Entire','There is a smooth transition from the top of the cap to its underside. No irregular attributes should be present on the edges. Also referred to as Smooth, Even, Seamless, Flush, or Regular.','',7, now(), now() ),
                                      (3,'Appendiculate','Remnants of a partial veil hang from the edge of the cap.','',7, now(), now() ),
                                      (4,'Striate','Fine and narrow stripes run parallel on the cap margins. The lines will often coincide with the gills underneath the cap. In some cases, the lines are only visible when the cap is wet. Also referred to as striped, furrowed, streaked, ribbed, lined,','',7, now(), now() ),
                                      (5,'Sulcate','Narrow parallel grooves that line the margins of the cap. Sulcate margins are more defined than striate but less ridged than plicated. Also referred to as plicate-striate.','',7, now(), now() ),
                                      (6,'Plicate','Parallel pleated margins. They are best described as fan-like or umbrella-like as if the surface of the cap were folded. Plicate margins are more defined and ridged than Striate or Sulcate. Also referred to as pleated or ridged.','',7, now(), now() ),
                                      (7,'Eroded','Deteriorated, gnawed, or eaten away. The disfigured margins are usually found in older specimens and are the result of insects or deliquescence (common with Ink Caps). Also referred to as gnawed or ragged.','',7, now(), now() ),
                                      (8,'Split','The edges of the cap are split apart or full of large crevices. Also referred to as cracked or rimose.','',7, now(), now() ),
                                      (9,'Lacerate','Many tears mark the edge of the cap. Similar to split margins, however, the cuts are smaller and more frequent. Also referred to as torn.','',7, now(), now() ),
                                      (10,'Undulating - Hairy','Hairy - The edges of the cap form a wave-like pattern as they rise and fall. Also referred to as wavy irregular or festoony.','',7, now(), now() ),
                                      (11,'Crenate - Hairy','Hairy - Semi-circle notches or round-toothed edges that are more blunted than serrate margins. Also referred to as scalloped.','',7, now(), now() ),
                                      (12,'Serrate - Hairy','Hairy - The edges of the cap appear jagged and saw-toothed. More pronounced than crenate margins.','',7, now(), now() );
INSERT INTO `pileus_shape_top_views` VALUES (1,'Not Entered','','',5, now(), now() ),
                                         (2,'Petaloid','petal','',5, now(), now() ),
                                         (3,'Spathulate','spatula','',5, now(), now() ),
                                         (4,'Dimidiate','1/2 circle','',5, now(), now() ),
                                         (5,'Flabelliform','fan-shaped','',5, now(), now() );
INSERT INTO `pileus_shapes` VALUES (1,'Not Entered','','',1,'2023-02-21 21:37:26','2023-02-21 21:37:26'),
                                (2,'Convex','evenly rounded','',5, now(), now() ),
                                (3,'Convex','evenly rounded','',5, now(), now() ),
                                (4,'ovoid','egg','',5, now(), now() ),
                                (5,'conic','cone','',5, now(), now() ),
                                (6,'campanulate','bell-shaped.','vv',5, now(), now() ),
                                (7,'parabolic','half-egg','',5, now(), now() ),
                                (8,'pulvinate','cushion','',5, now(), now() ),
                                (9,'cylindric','bullet','',5, now(), now() ),
                                (10,'plane','flat','',5, now(), now() ),
                                (11,'conchate','sea-shell','',5, now(), now() ),
                                (12,'umbonate','w/bump','',5, now(), now() ),
                                (13,'cuspidate','Umbonate with a pointy conical apex; Witch-hat shaped. also known as eye-tooth.','',5, now(), now() ),
                                (14,'papillate','w/nipple','',5, now(), now() ),
                                (15,'depressed','Saucer-shaped; The center is lower than the cap margin.','',5, now(), now() ),
                                (16,'umbilicate','a navel-like depression in the center.','',5, now(), now() ),
                                (17,'infundibuliform','funnel-shaped','',5, now(), now() );
INSERT INTO `pileus_surface_drynesses` VALUES (1,'Not Entered','','',5, now(), now() ),
                                           (2,'dry: Dull','','',5, now(), now() ),
                                           (3,'dry:  Silky','','',5, now(), now() ),
                                           (4,'Moist:  lubricous/greasy','','',5, now(), now() ),
                                           (5,'Moist: Viscid/sticky/tacky','','',5, now(), now() ),
                                           (6,'Moist: Glutinous (slimy)','','',5, now(), now() ),
                                           (7,'dry: Shiny','','',5, now(), now() );
INSERT INTO `pileus_surface_textures` VALUES (1,'Not Entered','','',1, now(), now() ),
                                          (2,'Smooth','No defining features found on the surface.','',7, now(), now() ),
                                          (3,'Uneven','A bumpy surface.','',7, now(), now() ),
                                          (4,'Rugose','A wrinkled or rough surface.','',7, now(), now() ),
                                          (5,'Rugulose','A slightly wrinkled surface.','',7, now(), now() ),
                                          (6,'Rivulose','A thinly wrinkled surface of branching wavy or crooked lines.','',7, now(), now() ),
                                          (7,'Scrobiculate','A pitted or furrowed surface.','',7, now(), now() ),
                                          (8,'Warty','Remnants of the universal veil remain on the surface in small patches.','',7, now(), now() ),
                                          (9,'Virgate','A streaked surface.','',7, now(), now() ),
                                          (10,'Hygrophanous','A surface that is transparent when wet and opaque when dry.','',7, now(), now() ),
                                          (11,'Sericeous','A silky surface.','',7, now(), now() ),
                                          (12,'Fibrillose','A surface covered in thread-like filaments.','',7, now(), now() ),
                                          (13,'Squamose','A surface covered with scales.','',7, now(), now() ),
                                          (14,'Squarrose','A ragged surface covered with small scales.','',7, now(), now() ),
                                          (15,'Pruinose','A surface covered with a white powdery frostlike substance.','',7, now(), now() ),
                                          (16,'Pulverulent','A surface covered with fine dust or powder.','',7, now(), now() ),
                                          (17,'Granulose','A surface covered in salt-like granulates.','',7, now(), now() ),
                                          (18,'Furfuraceous','A surface covered in flaky bran-like particles; dandruff-like.','',7, now(), now() ),
                                          (19,'Zonate','A surface containing zones or bands that are distinguished by texture or color.','',7, now(), now() ),
                                          (20,'Areolate','A cracked surface resembling dried-mud or paint.','',7, now(), now() ),
                                          (21,'Rimose','A surface covered in cracks and crevices.','',7, now(), now() ),
                                          (22,'Laccate','A waxy or lacquered surface texture.','',7, now(), now() ),
                                          (23, 'Viscid -','A sticky glue-like surface texture.','',7, now(), now() ),
                                          (24,'Glutinous','A slimy surface.','',7, now(), now() ),
                                          (25,'Glabrous - Hairy','Hairy - a bald surface.','',7, now(), now() ),
                                          (26,'Velvety - Hairy','Hairy - A surface covered with very fine and soft hairs.','',7, now(), now() ),
                                          (27,'Pubescent - Hairy','Hairy - A surface cover with fuzz or fine hairs.','',7, now(), now() ),
                                          (28,'Canescent - Hairy','Hairy - A surface covered in dense white or gray down-like hairs. Giving a frosted appearance.','',7, now(), now() ),
                                          (29,'Floccose - Hairy','Hairy - A surface covered in Wooly or cotton-like hairs.','',7, now(), now() ),
                                          (30,'Tomentose - Hairy','Hairy - A surface covered densely with matted hairs.','',7, now(), now() ),
                                          (31,'Hispid - Hairy','Hairy - A surface covered with straight bristle-like hairs.','',7, now(), now() ),
                                          (32,'Hirsute - Hairy','Hairy - A surface covered with slightly stiff and shaggy hairs.','',7, now(), now() ),
                                          (33,'Villose - Hairy','Hairy - A surface covered with long soft hairs.','',7, now(), now() ),
                                          (34,'Strigose - Hairy','Hairy - A surface covered with long bristle-like hairs.','',7, now(), now() );
INSERT INTO `chem_reactions` VALUES (1,'Not Entered','','',1, now(), now() ),
                                    (2,'Ammonia (NH4OH, Ammonium Hydroxide)','','',8, now(), now() ),
                                    (3,'KOH (Potassium Hydroxide) - 3%','','',8, now(), now() );
INSERT INTO `colors` VALUES (1,'Albus','White',1,'FFFFFF',1,255,255,255,'White',255,255,255,'../images/AMS_colors/colors/color_1.jpg', now(), now() ),
                            (2,'Griseus','Grullo',50,'A9A292',53,169,162,146,'Manatee',0,0,0,'../images/AMS_colors/colors/color_2.jpg', now(), now() ),
                            (3,'Murinus','Shadow',50,'857C6B',55,133,124,107,'Copper Rose',0,0,0,'../images/AMS_colors/colors/color_3.jpg', now(), now() ),
                            (4,'Ater','Dark Lava',50,'4B4435',57,75,68,53,'Olive Drab',0,0,0,'../images/AMS_colors/colors/color_4.jpg', now(), now() ),
                            (5,'Niger','Black',99,'000000',99,0,0,0,'Black',0,0,0,'../images/AMS_colors/colors/color_5.jpg', now(), now() ),
                            (6,'Fumosus','Pastel Brown',50,'7E6455',56,126,100,85,'Dim Gray',0,0,0,'../images/AMS_colors/colors/color_6.jpg', now(), now() ),
                            (7,'Avellaneus','Cafe au lait',70,'A97848',72,169,120,72,'Raw Umber',0,0,0,'../images/AMS_colors/colors/color_7.jpg', now(), now() ),
                            (8,'Isabellinus','Ruddy Brown',70,'BF7029',74,194,112,41,'Ruddy Brown',0,0,0,'../images/AMS_colors/colors/color_8.jpg', now(), now() ),
                            (9,'Umbrinus','Sepia',70,'6E4116',77,110,65,22,'Chocolate',0,0,0,'../images/AMS_colors/colors/color_9.jpg', now(), now() ),
                            (10,'Castaneus','Caput Mortuum',70,'5E2914',80,94,41,20,'Chocolate',0,0,0,'../images/AMS_colors/colors/color_10.jpg', now(), now() ),
                            (11,'Fuligineus','Zinnwaldite Brown',70,'391401',82,57,20,1,'Bulgarian Rose',0,0,0,'../images/AMS_colors/colors/color_11.jpg', now(), now() ),
                            (12,'Atropurpureus','Bulgarian Rose',70,'4E0F0F',84,78,15,15,'Rosewood',0,0,0,'../images/AMS_colors/colors/color_12.jpg', now(), now() ),
                            (13,'Purpureus','OU Crimson Red',10,'940101',10,148,1,1,'OU Crimson Red',0,0,0,'../images/AMS_colors/colors/color_13.jpg', now(), now() ),
                            (14,'Ruber','Rosso Corsa',10,'D30102',30,211,1,2,'Boston University Red',0,0,0,'../images/AMS_colors/colors/color_14.jpg', now(), now() ),
                            (15,'Miniatus','Coquelicot',10,'F73601',40,247,54,1,'Coquelicot',0,0,0,'../images/AMS_colors/colors/color_15.jpg', now(), now() ),
                            (16,'Incarnatus','Deep Carrot Orange',10,'ED7236',70,237,114,54,'Portland Orange',0,0,0,'../images/AMS_colors/colors/color_16.jpg', now(), now() ),
                            (17,'Roseus','Light Salmon',10,'F39F7C',90,243,159,124,'Atomic Tangerine',0,0,0,'../images/AMS_colors/colors/color_17.jpg', now(), now() ),
                            (18,'Testaceus','Flame',10,'DA5110',50,218,81,16,'Tenne (Tawny)',0,0,0,'../images/AMS_colors/colors/color_18.jpg', now(), now() ),
                            (19,'Latericius','Sienna',10,'97280A',20,151,40,10,'Brown',0,0,0,'../images/AMS_colors/colors/color_19.jpg', now(), now() ),
                            (20,'Badius','Caput Mortuum (also)',70,'561A10',81,86,26,16,'Chocolate',0,0,0,'../images/AMS_colors/colors/color_20.jpg', now(), now() ),
                            (21,'Aurantiacus','Safety Orange (Blaze Orange)',10,'EE6005',80,238,96,5,'Safety Orange',0,0,0,'../images/AMS_colors/colors/color_21.jpg', now(), now() ),
                            (22,'Luteus','Tangerine',40,'EE8801',49,238,136,1,'Orange',0,0,0,'../images/AMS_colors/colors/color_22.jpg', now(), now() ),
                            (23,'Flavus','UCLA Gold',40,'E7B001',48,231,176,1,'Orange',0,0,0,'../images/AMS_colors/colors/color_23.jpg', now(), now() ),
                            (24,'Citrinus','Meat brown',40,'DCC747',47,220,199,71,'Pear',0,0,0,'../images/AMS_colors/colors/color_24.jpg', now(), now() ),
                            (25,'Sulphureus','Straw',40,'DCCB71',43,220,203,113,'June Bud',0,0,0,'../images/AMS_colors/colors/color_25.jpg', now(), now() ),
                            (26,'Stramineus','Pale Gold',40,'E3CB95',41,227,203,149,'Medium Bud Spring',0,0,0,'../images/AMS_colors/colors/color_26.jpg', now(), now() ),
                            (27,'Cremeus','Pale Gold (also)',40,'E8C583',42,232,197,131,'Peach-Orange',0,0,0,'../images/AMS_colors/colors/color_27.jpg', now(), now() ),
                            (28,'Ochroleucus','Topaz',40,'F0C378',44,240,195,120,'Jonquil',0,0,0,'../images/AMS_colors/colors/color_28.jpg', now(), now() ),
                            (29,'Ochraceus','Pastel Orange',40,'F3B556',45,243,181,86,'Jonquil',0,0,0,'../images/AMS_colors/colors/color_29.jpg', now(), now() ),
                            (30,'Melleus','Indian Yellow',40,'DFB54F',46,21,81,79,'June Bud',0,0,0,'../images/AMS_colors/colors/color_30.jpg', now(), now() ),
                            (31,'Ferrunineus','Burnt Orange',10,'CB5607',60,203,86,7,'Tenne (Tawny)',0,0,0,'../images/AMS_colors/colors/color_31.jpg', now(), now() ),
                            (32,'Fulvus','Brown (Traditional)',70,'9E4410',78,158,68,16,'Brown',0,0,0,'../images/AMS_colors/colors/color_32.jpg', now(), now() ),
                            (33,'Flavo-virens','Brass',60,'B5AB3E',61,181,171,62,'Satin  Sheen Gold',0,0,0,'../images/AMS_colors/colors/color_33.jpg', now(), now() ),
                            (34,'Atro-virens','Myrtle',60,'213C25',65,33,60,37,'Olive Drab',0,0,0,'../images/AMS_colors/colors/color_34.jpg', now(), now() ),
                            (35,'Viridis','Fern Green',60,'4A7A3E',64,74,122,62,'Hunter Green',0,0,0,'../images/AMS_colors/colors/color_35.jpg', now(), now() ),
                            (36,'Prasinus','Fern Green',60,'6B8046',62,107,128,70,'Olive Drab',0,0,0,'../images/AMS_colors/colors/color_36.jpg', now(), now() ),
                            (37,'Aerugineus','Slate Gray',60,'6B938A',63,107,147,138,'Cadet Blue',0,0,0,'../images/AMS_colors/colors/color_37.jpg', now(), now() ),
                            (38,'Glaucus','Pastel Gray',50,'D6D5B7',51,214,213,183,'Pastel Gray',0,0,0,'../images/AMS_colors/colors/color_38.jpg', now(), now() ),
                            (39,'Olivaceus','Dark Brown',70,'5C4C1D',76,92,76,29,'Wine',0,0,0,'../images/AMS_colors/colors/color_39.jpg', now(), now() ),
                            (40,'Atro-cyaneus','Oxford Blue',20,'020F41',32,2,15,65,'Oxford Blue',0,0,0,'../images/AMS_colors/colors/color_40.jpg', now(), now() ),
                            (41,'Cyaneus','Royal Blue (Traditional)',20,'012866',22,1,40,102,'Dark Midnight Blue',0,0,0,'../images/AMS_colors/colors/color_41.jpg', now(), now() ),
                            (42,'Caeruleus','Moonstone Blue',20,'76A1BC',12,118,161,188,'Blue Gray',0,0,0,'../images/AMS_colors/colors/color_42.jpg', now(), now() ),
                            (43,'Caesius','Pale Silver',50,'C5C3AB',52,197,195,171,'Medium Spring Bud',0,0,0,'../images/AMS_colors/colors/color_43.jpg', now(), now() ),
                            (44,'Plumbeus','Battleship Gray',50,'858786',54,133,135,134,'Manatee',0,0,0,'../images/AMS_colors/colors/color_44.jpg', now(), now() ),
                            (45,'Ardesiacus','Rifle Green',60,'303C35',66,48,60,53,'Olive Drab',0,0,0,'../images/AMS_colors/colors/color_45.jpg', now(), now() ),
                            (46,'Atro-violaceus','Caput Mortuum (Also)',70,'491D31',79,73,29,49,'Olive Drab',0,0,0,'../images/AMS_colors/colors/color_46.jpg', now(), now() ),
                            (47,'Violaceus','French Lilac',70,'86728E',73,134,114,142,'French Lilac',0,0,0,'../images/AMS_colors/colors/color_47.jpg', now(), now() ),
                            (48,'Lilacinus','Puce',70,'C39AA1',71,195,154,161,'Puce',0,0,0,'../images/AMS_colors/colors/color_48.jpg', now(), now() ),
                            (49,'Lividus','Old Mauve',70,'6E3534',75,110,53,69,'Wine',0,0,0,'../images/AMS_colors/colors/color_49.jpg', now(), now() ),
                            (50,'Vinosus','Bulgarian Rose (Also)',70,'460910',83,70,9,16,'Bulgarian Rose',0,0,0,'../images/AMS_colors/colors/color_50.jpg', now(), now() );
INSERT INTO `countries` VALUES (1, 'USA', 'United States', '',  23, now(), now() ),
                               (2, 'MEX', 'Mexico',        '',  23, now(), now() ),
                               (3, 'CAN', 'Canada',        '',  23, now(), now() );
INSERT INTO `source_data_types` (`id`, `name`, `description`, `comments`, `created_at`, `updated_at`) VALUES
(1,'Not Entered','','', now(), now() ),
(2,'Book','','', now(), now() ),
(3,'Website','','', now(), now() ),
(4,'Magazine','','', now(), now() ),
(5,'Chart','like Scates','', now(), now() ),
(6,'Database','','', now(), now() );
INSERT INTO `source_data` (`id`, `title`, `author`, `ref`, `item_code`, `source_data_type`, `comment`,`created_at`, `updated_at`) VALUES
(1, 'Introductory Mycology', 'C. J. Alexopoulos, C. W. Mims,  M. Blackwell', NULL, 'https://amzn.to/4f8rMUJ', 2, 'I have Fourth Edition, Copyright 1996. Look for used.',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(2, 'Ainsworth & Bisbys Dictionary of the Fungi 10th Edition', 'P. M. Kirk, P. F. Cannon, D. W. Minter and J. A. Stalpers', NULL, 'https://amzn.to/49ztFZf', 2, 'Not light reading. ',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(3, 'Illustrated Dictionary of Mycology Second Edition', 'Miguel Ulloa and Richard T. Hanlin', NULL, 'https://amzn.to/3BwPADK', 2, 'Wonderful book with lot of information and incredible pictures.','2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(4, 'Mushrooms Demystified Second Edition', 'David Arora', NULL, 'https://amzn.to/3DdH511', 2, 'This is the one book to buy if you only buy one.',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(5, 'Easy Guide to Mushrooms Descriptions', 'Kit Scates', NULL, '', 5, 'Buy here: https://fungi.com/products/easy-mushroom-identification-charts You need this.',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(6, 'Easy Key to Common Gilled Mushrooms', 'Kit Scates', NULL, '', 5, 'Buy here: https://fungi.com/products/easy-mushroom-identification-charts  You need this.',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(7, 'https://mycologyst.art/mushroom-identification/mushroom-morphology', 'Unknown', NULL, '', 3, '', '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(8, 'www.mushroomexpert.com/index.html', 'Michael Kuo', NULL, '', 3, 'Kuo, Michael (2022). Mushroomexpert.com homepage. Retrieved April 5, 2022 from the Mushroomexpert.Com website: www.mushroomexpert.com/index.html',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(9, 'Fungal Families of the World', 'P. F. Cannon and P. M. Kirk', NULL, 'https://amzn.to/3OQaRLN', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(10, 'How to Know the Non-Gilled Fleshy Fungi', 'Helen V. Smith Alexander H. Smith', NULL, 'https://amzn.to/4iHnF50', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(11, 'How to Know the gilled mushrooms', 'Alexander H. Smith Helen V. Smith Nancy S. Weber', NULL, 'https://amzn.to/49AHy9O', 2, '', '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(12, 'National Audubon Society Field Guide to North American Mushrooms', 'Gary H. Lincoff', NULL, 'https://amzn.to/3BqkiP6', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(13, 'How to Identify Mushrooms to Genus I:  Macroscopic Features', 'David L. Largent', NULL, 'https://amzn.to/4ffAErE', 2, '', '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(14, 'How to Identify Mushrooms to Genus III:  Microscopic Features', 'David Largent David Johnson Roy Watling (Consultant)', NULL, 'https://amzn.to/49OABC9', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(15, 'Identification of the Larger Fungi Kindle Edition', 'Roy Watling', NULL, 'https://amzn.to/49wsI3S', 2, 'Be careful with this one if you attempt to get the paper version. The Kindle version text is good, but detail of the images is lacking. I tried to get the exact paper version and ran across some sort of duplicate ISBN number issue. ', '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(16, 'North American Mushrooms A Field Guide to Edible and Inedible Fungi', 'Dr. Orson K. Miller Jr. and Hope H. Miller', NULL, 'https://amzn.to/4gummUX', 2, '', '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(17, 'Mushrooms of the Southeast', 'Todd F. Elliott and Steven L. Stephenson', NULL, 'https://amzn.to/3OQpn6c', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(18, 'Mushrooms of the Gulf Coast States A Field Guide to Texas, Louisiana, Mississippi, Alabama, and Florida', 'Alan E. Bessette Arleen R. Bessette David P. Lewis', NULL, 'https://amzn.to/4gNz3ur', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(19, 'Mushrooms How to Identify and Gather Wild Mushrooms and Other Fungi', 'DK? Thomas Lessoe?', NULL, 'https://amzn.to/4fhE9O6', 2, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(20, 'Mushrooms of the Midwest', 'Michael Kuo and Andrew S. Methven', NULL, 'https://amzn.to/4g9yOtF', 2, 'Michael Kuo of The Mushroom Expert website',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(21, 'North American Boletes A Color Guide to the Fleshy Pored Mushrooms', 'Alan E. Bessette, William C. Roody, and Arleen R. Bessette', NULL, 'https://amzn.to/3ZPxKoM', 2, '',   '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(22, 'MBList', '', NULL, '', 6, '',  '2023-07-10 00:00:00', '2023-07-10 00:00:00'),
(23, 'Will Johnston', 'Will Johnston', NULL, '', 1, '',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(24, 'Comparison of Different Drying Methods for Recovery of Mushroom DNA', 'Shouxian Wang - corresponding author Yu Liu and Jianping Xu corresponding author', NULL, '', 3, 'Wang S, Liu Y, Xu J. Comparison of Different Drying Methods for Recovery of Mushroom DNA. Sci Rep. 2017 Jun 7;7(1):3008. doi: 10.1038/s41598-017-03570-7. PMID: 28592865; PMCID: PMC5462775.',  '2024-06-02 10:05:27', '2024-06-02 10:05:27'),
(26, 'The Beginners Guide to Mushrooms', 'Britt A. Bunyard & Tavis Lynch', '', 'https://amzn.to/3ZxHO4B', 5, '',    now(), now() ),
(27, 'The Lives of Fungi A Natural History of Our Planets Decomposers', 'Britt A. Bunyard', '', 'https://amzn.to/3BqJwNi', 5, '',   now(), now() ),
(28, 'An Introductory To The Taxonomy And Nomenclature Of Fungi', 'G. R. Bisby, M.A., Ph.D.', '', '', 5, 'Copyright 1945, may be hard to come by. Dictionary of the Fungi is known as Ainsworth & Bisbys Dictionary Of The Fungi. That Bisby.',    now(), now() ),
(29, 'Edible Wild Mushroom Foraging and Identification Presented by the Alabama Mushroom Society', 'Anthoni Goodman PhD', '', '', 5, 'Buy Here:  https://alabamamushroomsociety.org/recommended-books',   now(), now() ),
(31, 'Healing Mushrooms A Practical Guide to Medicinal Mushrooms', 'Richard Bray', '', 'https://amzn.to/4gm4tHY', 5, '',    now(), now() ),
(32, 'Studying the DISCOMYCETES from initiation to advance levels', 'René Dougoud with collaboratin of Jean-Paul Priou & Nicolas Van Vooren', '', '', 5, '',   now(), now() ),
(33, 'Methuen Handbook of Colour', 'Eyre Methuen', '', 'https://amzn.to/3Vw6n0A', 5, 'You either go all in on colors or you do not. My copy is copyright 1981.',    now(), now() ),
(34, 'A Field Guide to Southern Mushrooms', 'Nancy Smith Weber and Alexander H. Smith', '', 'https://amzn.to/4fcjWte', 5, '',    now(), now() ),
(35, 'The Mushroom Hunters Field Guide', 'Alexander H. Smith and Nancy Smith Weber', '', 'https://amzn.to/4iuFEeM', 5, '',   now(), now() ),
(36, 'Biodiversity of FUNGI Inventory and Monitoring Methods', 'edited by: Gregory M. Mueller, Gerald F. Bills and Mercedes S. Foster', '', 'https://amzn.to/3BoHM74', 5, '',   now(), now() ),
(37, 'AGARICUS of NORTH AMERICA', 'Richard W. Kerrigan', '', 'https://amzn.to/4ixFeUN', 5, '',   now(), now() ),
(38, 'how to know the lichens', 'Mason E. Hale', '', 'https://amzn.to/4iA5HBp', 5, 'Another older book, copyright 1979',    now(), now() ),
(39, 'The Fungal Pharmacy', 'Robert Rogers', '', 'https://amzn.to/4g7sq6c', 5, '',    now(), now() ),
(40, 'A Mushroom Word Guide', 'Robert M Hallock, PhD', '', 'https://amzn.to/4gbl4hO', 5, '',   now(), now() ),
(41, 'The Complete Mushroom Hunter', 'Gary Lincoff', '', 'https://amzn.to/41vz7uf', 5, '',    now(), now() ),
(42, 'Mushrooms Of Mississippi and Other Fungi and Protists', 'George H. Dukes Jr.', '', 'https://amzn.to/3ZQFwPz', 5, '',  now(), now() ),
(43, 'Molecular Markers in Mycology', 'Bhim Pratap and Singh Vijai Kumar Gupta Editors', '', 'https://amzn.to/49yEbju', 5, '',    now(), now() );
INSERT INTO `display_options` VALUES (1,'Not Entered','','',1, now(), now() ),
                                     (2,'text_box_number_mm','','',1, now(), now() ),
                                     (3,'text_box_number_um','','',1, now(), now() ),
                                     (4,'text_box_number','','',1, now(), now() ),
                                     (5,'text_box_string','','',1, now(), now() ),
                                     (6,'color','','',1, now(), now() ),
                                     (7,'taste','','',1, now(), now() ),
                                     (8,'odor','','',1, now(), now() ),
                                     (9,'radio','','',1, now(), now() ),
                                     (10,'drop-down','','',1, now(), now() ),
                                     (11,'state','','',1, now(), now() ),
                                     (12,'country','','',1, now(), now() ),
                                     (13,'texture','','',1, now(), now() ),
                                     (14,'yes no','','',1,now(), now() ),
                                     (15,'abundance','','',1,now(), now() ),
                                     (16,'text box number grams measurement','','',1,now(), now() ),
                                     (17,'Genus Species','','',1,now(), now() );
INSERT INTO `fungus_types` VALUES (1,'Not Entered','','',1, now(), now() ),
                                  (2,'Lamella - Gills','','',1, now(), now() ),
                                  (3,'Pores','','',1, now(), now() ),
                                  (4,'Teeth','','',1, now(), now() ),
                                  (5,'Cups','','',1, now(), now() ),
                                  (6,'Stinkhorn','','',1, now(), now() );
INSERT INTO `lamella_attachments` VALUES (1,'Not Entered','','',1, now(), now() ),
                                      (2,'Free - remote','','',5, now(), now() ),
                                      (3,'Free - close','','',5, now(), now() ),
                                      (4,'Adnate - horizontal','','',5, now(), now() ),
                                      (5,'Adnate - ascending','','',5, now(), now() ),
                                      (6,'Adnexed (almost free)','','',5, now(), now() ),
                                      (7,'Sinuate','','',5, now(), now() ),
                                      (8,'Emarginate (notched)','','',5, now(), now() ),
                                      (9,'Decurrent - long','','',5, now(), now() ),
                                      (10,'Decurrent - short','','',5, now(), now() ),
                                      (11,'Seceding (breaking away)','','',5, now(), now() ),
                                      (12,'Uncinate (w/decurrent tooth)','','',5, now(), now() ),
                                      (13,'Collared','Gills are attached to a collar or ring that encircles the stipe.','',7, now(), now() );
INSERT INTO `lamella_breadths` VALUES (1,'Not Entered','','',1, now(), now() ),
                                   (2,'Broad','','',5, now(), now() ),
                                   (3,'Free - close','','',5, now(), now() ),
                                   (4,'Ventricose','','',5, now(), now() );
INSERT INTO `lamella_edges` VALUES (1,'Not Entered','','',1, now(), now() ),
                                (2,'Even - entire','','',5, now(), now() ),
                                (3,'Serrate','','',5, now(), now() ),
                                (4,'Serrulate','','',5, now(), now() ),
                                (5,'Eroded (\"gnawed\")','','',5, now(), now() ),
                                (6,'Fimbriate (fringed)','','',5, now(), now() ),
                                (7,'Marginate (diff. color)','','',5, now(), now() ),
                                (8,'Crenate (scalloped)','','',5, now(), now() ),
                                (9,'Acute','','',5, now(), now() ),
                                (10,'Obtuse (blunt)','','',5, now(), now() ),
                                (11,'Crisped (crinkled)','','',5, now(), now() );
INSERT INTO `lamella_spacings` VALUES (1,'Not Entered','','',1, now(), now() ),
                                   (2,'Crowded','The Gills are tightly close together.','',7, now(), now() ),
                                   (3,'Close','The Gills are close together.','',7, now(), now() ),
                                   (4,'Subdistant','The gills are spaced apart.','',7, now(), now() ),
                                   (5,'Distant','The gills are widely spaced apart.','',7, now(), now() );
INSERT INTO `lamella_thicknesses` VALUES (1,'Not Entered','','',1, now(), now() ),
                                    (2,'Average','','',5, now(), now() ),
                                    (3,'Thick','','',5, now(), now() ),
                                    (4,'Tapering','','',5, now(), now() );
INSERT INTO `habitats` VALUES (1,'Not Entered','','',1, now(), now() ),
                              (2,'Terrestrial (on soil - bare )','','',5, now(), now() ),
                              (3,'Terrestrial (on soil - burned )','','',5, now(), now() ),
                              (4,'Terrestrial (on soil - disturbed )','','',5, now(), now() ),
                              (5,'Lignicolous (on wood) - what kind of tree?','','',5, now(), now() ),
                              (6,'Humicolous (on humus, duff) - conifer, other?','','',5, now(), now() ),
                              (7,'Coprophious (on dung) what kind?','','',5, now(), now() ),
                              (8,'In grassy area - lawn, pasture, etc?','','',5, now(), now() ),
                              (9,'In forest - conifer, hardwood, mixed?','','',5, now(), now() ),
                              (16,'fungicolous','mushroom mycelia grow in other mushrooms','p 7, How to Identify Mushrooms to Genus I: Macroscopic Features - David L. Largent',13,'2023-03-16 21:46:17','2023-03-16 21:46:17');
INSERT INTO `habits` VALUES (1,'Not Entered','','',1, now(), now() ),
                            (2,'Single, solitary','','',5, now(), now() ),
                            (3,'Scattered (1-2 feet apart)','','',5, now(), now() ),
                            (4,'Gregarious (growing in a group)','','',5, now(), now() ),
                            (5,'Caespitose (clustered, not joined)','','',5, now(), now() ),
                            (6,'Connate (fused at base)','','',5, now(), now() ),
                            (7,'Imbricate (overlapping)','','',5, now(), now() ),
                            (8,'In troops or rings','','',5, now(), now() );
INSERT INTO `lens` VALUES (1,'Not Entered','','','', now(), now() ),
                          (2,'Nikon','Nikon ED AF Micro Nikkor 70-180mm 1:4.5-5.6 D','','', now(), now() );
INSERT INTO `odors` VALUES (1,'Not Entered','','',1, now(), now() ),
                           (2,'None','','',5, now(), now() ),
                           (3,'Fruity','','',5, now(), now() ),
                           (4,'Lemony','','',5, now(), now() ),
                           (5,'Anise (licorice)','','',5, now(), now() ),
                           (6,'Farinaceous (like fresh meal)','','',5, now(), now() ),
                           (7,'Pungent','','',5, now(), now() ),
                           (8,'Nauseous','','',5, now(), now() ),
                           (9,'Nitrous','','',5, now(), now() ),
                           (10,'Earthy','','',5, now(), now() ),
                           (11,'Spermatic','','',5, now(), now() ),
                           (12,'Garlic','','',4, now(), now() ),
                           (13,'Maraschino cherries','','',4, now(), now() ),
                           (14,'Sewer gas','','',4, now(), now() ),
                           (15,'spicy - red hots - dirty socks','','',4, now(), now() );
INSERT INTO `partial_inner_veil_annular_ring_positions` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                               (2,'None','Does not have annulus ring','',5, now(), now() ),
                                                               (3,'Superior','Near the cap','',5, now(), now() ),
                                                               (4,'Apical','upper half','',5, now(), now() ),
                                                               (5,'Median','in the middle','',5, now(), now() ),
                                                               (6,'Inferior','Lower half','',5, now(), now() ),
                                                               (7,'Basal','Near the base','',5, now(), now() );
INSERT INTO `partial_inner_veil_appearances` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                    (2,'Two Rings (from 2 veils)','','',5, now(), now() ),
                                                    (3,'Doubly-flared Ring','','',5, now(), now() ),
                                                    (4,'\"Cogwheel\" Stellate','','',5, now(), now() ),
                                                    (5,'Floccose (downy tuffs)','','',5, now(), now() ),
                                                    (6,'Cortinate PV & Fibrillose Annular Zone','','',5, now(), now() ),
                                                    (7,'Single Ring thick on edge','','',5, now(), now() ),
                                                    (8,'Pendant (hanging)','','',5, now(), now() ),
                                                    (9,'Subperonate','','',5, now(), now() ),
                                                    (10,'Peronate (w/\"boot\")','','',5, now(), now() );
INSERT INTO `partial_inner_veil_fates` VALUES (1,'Not Entered','','',1, now(), now() ),
                                              (2,'Disappearing - Evanescent','can only be detected in button stage','',4, now(), now() ),
                                              (3,'Persistent','leaving remnants on cap','',4, now(), now() );
INSERT INTO `partial_inner_veil_textures` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                 (2,'Membranous (skin-like)','','',5, now(), now() ),
                                                 (3,'Cortinate (cobwebby)','','',5, now(), now() ),
                                                 (4,'Fibillose (thready)','','',5, now(), now() ),
                                                 (5,'Gelatinous (slimy)','','',5, now(), now() );
INSERT INTO `parts` VALUES (1,'Not Entered','','',1, now(), now() ),
                           (2,'Basic','default data that every specimen will have','',5, now(), now() ),
                           (3,'Macro - Pileus - Cap','','',5, now(), now() ),
                           (4,'Macro - Lamellae - Gills','','',5, now(), now() ),
                           (5,'Macro - Stipe - Stem','','',5, now(), now() ),
                           (6,'Macro - Veil','','',5, now(), now() ),
                           (7,'Macro - Mycelium','','',5, now(), now() ),
                           (8,'Macro - Spores','micro for spores is here - not in micro','',5, now(), now() ),
                           (9,'Macro - Chemical Reaction','','',5, now(), now() ),
                           (10,'Macro -General','','',5, now(), now() ),
                           (11,'Low Magnification','','',5, now(), now() ),
                           (12,'Micro - Pileus - Cap','','',5, now(), now() ),
                           (13,'Micro - Lamellae - Gills','','',5, now(), now() ),
                           (14,'Micro - Stipe - Stem','','',5, now(), now() ),
                           (15,'Micro - Veil','','',5, now(), now() ),
                           (16,'Micro - Mycelium','','',5, now(), now() ),
                           (17,'Micro - Spores','','',5, now(), now() ),
                           (18,'Micro - Chemical Reaction','','',5, now(), now() ),
                           (19,'Micro -General','','',5, now(), now() ),
                           (20,'DNA','','',5, now(), now() ),
                           (21,'Habitat','Habitat, Plant Assoc ','',5, now(), now() ),
                           (22,'Rhizomorph','','',5, now(), now() ),
                           (23,'Color','this will allow color selection for ALL color characters to be in one place','',1, now(), now() ),
                           (24,'Location','lat lon city county state country','',1, now(), now() ),
                           (25,'Identification','species genus inaturalist etc','',1, now(), now() ),
                           (26,'Storage','','',1, now(), now() ),
                           (27,'Other','','',5, now(), now() ),
                           (28,'Undecided','','',5, now(), now() );
INSERT INTO `permissions` (`id`, `name`, `description`, `comments`, `created_at`, `updated_at`) VALUES    (1,'Owner','','', now(), now() ),
                                                                                                          (2,'Admin','','', now(), now() ),
                                                                                                          (3,'Expert','','', now(), now() ),
                                                                                                          (4,'Scholar','','', now(), now() ),
                                                                                                          (5,'Author','','', now(), now() ),
                                                                                                          (6,'Editor','','', now(), now() ),
                                                                                                          (7,'Contributor','','', now(), now() ),
                                                                                                          (8,'Developer','','', now(), now() ),
                                                                                                          (9,'Member','','', now(), now() );


INSERT INTO `soil_types` VALUES (1,'Not Entered','','',1, now(), now() ),
                                (2,'Unknown','','',1, now(), now() ),
                                (3,'Loam','','',1, now(), now() );
INSERT INTO `mushroom_ages` VALUES (1,'Not Entered','','',1, now(), now() ),
                                   (2,'Button','very young','',1, now(), now() ),
                                   (3,'Young','','',1, now(), now() ),
                                   (4,'Mature','','',1, now(), now() ),
                                   (5,'Past Prime','','',1, now(), now() );
INSERT INTO `mushroom_storage_locations` VALUES (1,'Not Entered','Not Entered','None',1, now(), now() ),
                                                (2,'Observation Only - No specimen collected','','None',2, now(), now() ),
                                                (3,'Specimen Collector','This is you, if you collected this specimen','',2, now(), now() ),
                                                (4,'Herbarium','','',2, now(), now() );
INSERT INTO `states` VALUES (1,'Alabama','','',1, now(), now() ),
                            (2,'Alaska','','',1, now(), now() ),
                            (3,'Arizona','','',1, now(), now() ),
                            (4,'Arkansas','','',1, now(), now() ),
                            (5,'California','','',1, now(), now() ),
                            (6,'Colorado','','',1, now(), now() ),
                            (7,'Connecticut','','',1, now(), now() ),
                            (8,'Delaware','','',1, now(), now() ),
                            (9,'District of Columbia','','',1, now(), now() ),
                            (10,'Florida','','',1, now(), now() ),
                            (11,'Georgia','','',1, now(), now() ),
                            (12,'Hawaii','','',1, now(), now() ),
                            (13,'Idaho','','',1, now(), now() ),
                            (14,'Illinois','','',1, now(), now() ),
                            (15,'Indiana','','',1, now(), now() ),
                            (16,'Iowa','','',1, now(), now() ),
                            (17,'Kansas','','',1, now(), now() ),
                            (18,'Kentucky','','',1, now(), now() ),
                            (19,'Louisiana','','',1, now(), now() ),
                            (20,'Maine','','',1, now(), now() ),
                            (21,'Maryland','','',1, now(), now() ),
                            (22,'Massachusetts','','',1, now(), now() ),
                            (23,'Michigan','','',1, now(), now() ),
                            (24,'Minnesota','','',1, now(), now() ),
                            (25,'Mississippi','','',1, now(), now() ),
                            (26,'Missouri','','',1, now(), now() ),
                            (27,'Montana','','',1, now(), now() ),
                            (28,'Nebraska','','',1, now(), now() ),
                            (29,'Nevada','','',1, now(), now() ),
                            (30,'New Hampshire','','',1, now(), now() ),
                            (31,'New Jersey','','',1, now(), now() ),
                            (32,'New Mexico','','',1, now(), now() ),
                            (33,'New York','','',1, now(), now() ),
                            (34,'North Carolina','','',1, now(), now() ),
                            (35,'North Dakota','','',1, now(), now() ),
                            (36,'Ohio','','',1, now(), now() ),
                            (37,'Oklahoma','','',1, now(), now() ),
                            (38,'Oregon','','',1, now(), now() ),
                            (39,'Pennsylvania','','',1, now(), now() ),
                            (40,'Rhode Island','','',1, now(), now() ),
                            (41,'South Carolina','','',1, now(), now() ),
                            (42,'South Dakota','','',1, now(), now() ),
                            (43,'Tennessee','','',1, now(), now() ),
                            (44,'Texas','','',1, now(), now() ),
                            (45,'Utah','','',1, now(), now() ),
                            (46,'Vermont','','',1, now(), now() ),
                            (47,'Virginia','','',1, now(), now() ),
                            (48,'Washington','','',1, now(), now() ),
                            (49,'West Virginia','','',1, now(), now() ),
                            (50,'Wisconsin','','',1, now(), now() ),
                            (51,'Wyoming','','',1, now(), now() ),
                            (52,'Alberta','','',3, now(), now() ),
                            (53,'British Columbia','','',3, now(), now() ),
                            (54,'Manitoba','','',3, now(), now() ),
                            (55,'New Brunswick','','',3, now(), now() ),
                            (56,'Newfoundland','','',3, now(), now() ),
                            (57,'Nova Scotia','','',3, now(), now() ),
                            (58,'Northwest Territories','','',3, now(), now() ),
                            (59,'Nunavut','','',3, now(), now() ),
                            (60,'Ontario','','',3, now(), now() ),
                            (61,'Prince Edward Island','','',3, now(), now() ),
                            (62,'Quebec','','',3, now(), now() ),
                            (63,'Saskatchewan','','',3, now(), now() ),
                            (64,'Yukon','','',3, now(), now() ),
                            (65,'Aguascalientes','','',2, now(), now() ),
                            (66,'Baja California','','',2, now(), now() ),
                            (67,'Baja California Sur','','',2, now(), now() ),
                            (68,'Campeche','','',2, now(), now() ),
                            (69,'Chiapas','','',2, now(), now() ),
                            (70,'Chihuahua','','',2, now(), now() ),
                            (71,'Coahuila','','',2, now(), now() ),
                            (72,'Colima','','',2, now(), now() ),
                            (73,'Distrito Federal','','',2, now(), now() ),
                            (74,'Durango','','',2, now(), now() ),
                            (75,'Guanajuato','','',2, now(), now() ),
                            (76,'Guerrero','','',2, now(), now() ),
                            (77,'Hidalgo','','',2, now(), now() ),
                            (78,'Jalisco','','',2, now(), now() ),
                            (79,'Mexico','','',2, now(), now() ),
                            (80,'Michoacan','','',2, now(), now() ),
                            (81,'Morelos','','',2, now(), now() ),
                            (82,'Nayarit','','',2, now(), now() ),
                            (83,'Nuevo Leon','','',2, now(), now() ),
                            (84,'Oaxaca','','',2, now(), now() ),
                            (85,'Puebla','','',2, now(), now() ),
                            (86,'Queretaro','','',2, now(), now() ),
                            (87,'Quintana Roo','','',2, now(), now() ),
                            (88,'San Luis Potosi','','',2, now(), now() ),
                            (89,'Sinaloa','','',2, now(), now() ),
                            (90,'Sonora','','',2, now(), now() ),
                            (91,'Tabasco','','',2, now(), now() ),
                            (92,'Tamaulipas','','',2, now(), now() ),
                            (93,'Tlaxcala','','',2, now(), now() ),
                            (94,'Veracruz','','',2, now(), now() ),
                            (95,'Yucatan','','',2, now(), now() ),
                            (96,'Zacatecas','','',2, now(), now() );
INSERT INTO `stipe_interiors` VALUES (1, 'Not Entered',       '','', 1, now(), now() ),
                                    (2,  'Solid',             '','', 5, now(), now() ),
                                    (3,  'Hollow - fistulose','','', 5, now(), now() ),
                                    (4,  'Tubular',           '','', 5, now(), now() ),
                                    (5,  'Cavernous',         '','', 5, now(), now() ),
                                    (6,  'Stuffed with pith', '','', 5, now(), now() );
INSERT INTO `stipe_locations` VALUES (1,'Not Entered','','',1, now(), now() ),
                                    (2,'Central','','',5, now(), now() ),
                                    (3,'Eccentric - off-center','','',5, now(), now() ),
                                    (4,'Lateral - attached at margin','','',5, now(), now() ),
                                    (5,'Sessile - missing','','',5, now(), now() );
INSERT INTO `stipe_shapes` VALUES (1,'Not Entered','','',1, now(), now() ),
                                 (2,'Terete (round)','','',5, now(), now() ),
                                 (3,'Compressed (flattened)','','',5, now(), now() ),
                                 (4,'Equal','','',5, now(), now() ),
                                 (5,'Clavate (club)','','',5, now(), now() ),
                                 (6,'Radicating (w/\"root\")','','',5, now(), now() ),
                                 (7,'Flexous','','',5, now(), now() ),
                                 (8,'Ventricose Fusiform','','',5, now(), now() ),
                                 (9,'Tapering','','',5, now(), now() ),
                                 (10,'Abruptly bulbous','','',5, now(), now() ),
                                 (11,'Rounded','','',5, now(), now() ),
                                 (12,'Oblique (angle)','','',5, now(), now() ),
                                 (13,'Marginate','','',5, now(), now() );
INSERT INTO `stipe_surfaces` VALUES (1,'Not Entered','','',1, now(), now() ),
                                   (2,'Smooth','No defining features found on the surface.','',7, now(), now() ),
                                   (3,'Uneven','A bumpy surface.','',7, now(), now() ),
                                   (4,'Rugose','A wrinkled or rough surface.','',7, now(), now() ),
                                   (5,'Rugulose','A slightly wrinkled surface.','',7, now(), now() ),
                                   (6,'Rivulose','A thinly wrinkled surface of branching wavy or crooked lines.','',7, now(), now() ),
                                   (7,'Scrobiculate','A pitted or furrowed surface.','',7, now(), now() ),
                                   (8,'Warty','Remnants of the universal veil remain on the surface in small patches.','',7, now(), now() ),
                                   (9,'Virgate','A streaked surface.','',7, now(), now() ),
                                   (10,'Hygrophanous','A surface that is transparent when wet and opaque when dry.','',7, now(), now() ),
                                   (11,'Sericeous','A silky surface.','',7, now(), now() ),
                                   (12,'Fibrillose','A surface covered in thread-like filaments.','',7, now(), now() ),
                                   (13,'Squamose','A surface covered with scales.','',7, now(), now() ),
                                   (14,'Squarrose','A ragged surface covered with small scales.','',7, now(), now() ),
                                   (15,'Pruinose','A surface covered with a white powdery frostlike substance.','',7, now(), now() ),
                                   (16,'Pulverulent','A surface covered with fine dust or powder.','',7, now(), now() ),
                                   (17,'Granulose','A surface covered in salt-like granulates.','',7, now(), now() ),
                                   (18,'Furfuraceous','A surface covered in flaky bran-like particles; dandruff-like.','',7, now(), now() ),
                                   (19,'Zonate','A surface containing zones or bands that are distinguished by texture or color.','',7, now(), now() ),
                                   (20,'Areolate','A cracked surface resembling dried-mud or paint.','',7, now(), now() ),
                                   (21,'Rimose','A surface covered in cracks and crevices.','',7, now(), now() ),
                                   (22,'Laccate','A waxy or lacquered surface texture.','',7, now(), now() ),
                                   (23, 'Viscid -','A sticky glue-like surface texture.','',7, now(), now() ),
                                   (24,'Glutinous','A slimy surface.','',7, now(), now() ),
                                   (25,'Glabrous - Hairy','Hairy - a bald surface.','',7, now(), now() ),
                                   (26,'Velvety - Hairy','Hairy - A surface covered with very fine and soft hairs.','',7, now(), now() ),
                                   (27,'Pubescent - Hairy','Hairy - A surface cover with fuzz or fine hairs.','',7, now(), now() ),
                                   (28,'Canescent - Hairy','Hairy - A surface covered in dense white or gray down-like hairs. Giving a frosted appearance.','',7, now(), now() ),
                                   (29,'Floccose - Hairy','Hairy - A surface covered in Wooly or cotton-like hairs.','',7, now(), now() ),
                                   (30,'Tomentose - Hairy','Hairy - A surface covered densely with matted hairs.','',7, now(), now() ),
                                   (31,'Hispid - Hairy','Hairy - A surface covered with straight bristle-like hairs.','',7, now(), now() ),
                                   (32,'Hirsute - Hairy','Hairy - A surface covered with slightly stiff and shaggy hairs.','',7, now(), now() ),
                                   (33,'Villose - Hairy','Hairy - A surface covered with long soft hairs.','',7, now(), now() ),
                                   (34,'Strigose - Hairy','Hairy - A surface covered with long bristle-like hairs.','',7, now(), now() ),
                                   (35,'Banded','','',5, now(), now() ),
                                   (36,'Peronate','','',5, now(), now() ),
                                   (37,'Fibrous','','',5, now(), now() ),
                                   (38,'Lacunose (w/dp.grooves)','','',5, now(), now() ),
                                   (39,'Longitudinally striate','','',5, now(), now() ),
                                   (40,'Ribbed/Costate','','',5, now(), now() ),
                                   (41,'Scabrous (scabby)','','',5, now(), now() ),
                                   (42,'Punctuate (w/small dots)','','',5, now(), now() ),
                                   (43,'Glanular-dotted (w/dark sticky dots)','','',5, now(), now() ),
                                   (44,'Reticulate (fishnet)','','',5, now(), now() );
INSERT INTO `stipe_textures` VALUES (1,'Not Entered','','',1, now(), now() ),
                                   (2,'Fragile','','',5, now(), now() ),
                                   (3,'Pliable','','',5, now(), now() ),
                                   (4,'Chalky','','',5, now(), now() ),
                                   (5,'Rigid','','',5, now(), now() ),
                                   (6,'Fibrous (Fleshy-Fibrous)','usually rather thick, and when broken in two, leaves a ragged edge.','',5, now(), now() ),
                                   (7,'Cartilaginous','Common stipe, usually thin and breaks with a firm split when bent in two, similar to cartilage.','',13, now(), now() ),
                                   (8,'Firm','','',5, now(), now() ),
                                   (9,'Woody','','',13, now(), now() ),
                                   (10,'Corky','','',13, now(), now() ),
                                   (11,'Leathery (coriaceous)','','',13, now(), now() ),
                                   (12,'Chalky','feels and breaks like chalk in hand. When crushed, it breaks up into powder or chunks.','',13, now(), now() ),
                                   (13,'Breaking with a snap','','',5, now(), now() );
INSERT INTO `synonyms` VALUES (1,'epigeous','above-ground ','',2, now(), now() ),
                              (2,'hypogeous','underground','',2, now(), now() ),
                              (3,'mushroom','fruiting body of a fungus','',2, now(), now() ),
                              (4,'basidiocarp','fruiting body','',2, now(), now() ),
                              (5,'thallus','soma','entire body of fungus',2, now(), now() ),
                              (6,'sporocarp','fruiting body','',2, now(), now() ),
                              (7,'pileus','cap','',2, now(), now() ),
                              (8,'Stipe','Stalk','',2, now(), now() ),
                              (9,'Gills','Lamellae','',2, now(), now() ),
                              (10,'Volva','cup','',2, now(), now() ),
                              (11,'Annulus','ring','',2, now(), now() ),
                              (12,'cone','conical','',5, now(), now() ),
                              (13,'conic','conical','',5, now(), now() ),
                              (14,'disc','center','',5, now(), now() ),
                              (15,'margin','edge','',5, now(), now() ),
                              (16,'ring','annulus','',5, now(), now() ),
                              (17,'stem','stipe','',5, now(), now() ),
                              (18,'volva','cup','',5, now(), now() ),
                              (19,'convex','evenly rounded','',1, now(), now() ),
                              (20,'ovoid','egg','',5, now(), now() ),
                              (21,'campanulate','bell-shaped','',5, now(), now() ),
                              (22,'parabolic','half-egg','',5, now(), now() ),
                              (23,'pulvinate','cushion','',5, now(), now() ),
                              (24,'cylindric','bullet','',5, now(), now() ),
                              (25,'plane','flat','',5, now(), now() );
INSERT INTO `tastes` VALUES (1,'Not Entered','','',1, now(), now() ),
                            (2,'None','','',5, now(), now() ),
                            (3,'Mild','','',5, now(), now() ),
                            (4,'Bitter','','',5, now(), now() ),
                            (5,'Acrid (= puckery? astringent)/Peppery','','',5, now(), now() ),
                            (6,'Agreeable','','',5, now(), now() ),
                            (7,'Farinaceous (like fresh meal)','','',5, now(), now() );
INSERT INTO `toxics` VALUES (1,'Not Entered','','',2, now(), now() ),
                            (2,'Not Toxic','','',2, now(), now() ),
                            (3,'Toxic','','',2, now(), now() );
INSERT INTO `universal_outer_veil_appearances` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                      (2,'Two Rings (from 2 veils)','','',5, now(), now() ),
                                                      (3,'Doubly-flared Ring','','',5, now(), now() ),
                                                      (4,'\"Cogwheel\" Stellate','','',5, now(), now() ),
                                                      (5,'Floccose (downy tuffs)','','',5, now(), now() ),
                                                      (6,'Cortinate PV & Fibrillose Annular Zone','','',5, now(), now() ),
                                                      (7,'Single Ring thick on edge','','',5, now(), now() ),
                                                      (8,'Pendant (hanging)','','',5, now(), now() ),
                                                      (9,'Subperonate','','',5, now(), now() ),
                                                      (10,'Peronate (w/\"boot\")','','',5, now(), now() );
INSERT INTO `universal_outer_veil_fates` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                (2,'Disappearing','','',5, now(), now() ),
                                                (3,'Leaving fragments on cap','','',5, now(), now() );
INSERT INTO `universal_outer_veil_textures` VALUES (1,'Not Entered','','',1, now(), now() ),
                                                   (2,'Membranous (skin-like)','','',5, now(), now() ),
                                                   (3,'Cortinate (cobwebby)','','',5, now(), now() ),
                                                   (4,'Fibillose (thready)','','',5, now(), now() ),
                                                   (5,'Gelatinous (slimy)','','',5, now(), now() );
INSERT INTO `veils` VALUES (1,'Not Entered','','',1, now(), now() ),
                           (2,'Flaring','The annulus is flaring upwards.','',7, now(), now() ),
                           (3,'Pendant','The veil is hanging downward from the stipe.','',7, now(), now() ),
                           (4,'Double Rings','Two visible veils..','',7, now(), now() ),
                           (5,'Ring Zone','The stipe is marked with the remnants of the annulus','',7, now(), now() ),
                           (6,'Cortinate','The partial veil is cobweb-like or tread-like (Fibrillose)..','',7, now(), now() ),
                           (7,'Stellate','The partial veil resembles a cogwheel.','',7, now(), now() ),
                           (8,'Floccose','The partial veil is fluffy and down-like.','',7, now(), now() ),
                           (9,'Peronate','The stipe resembles a sheath-like boot or stocking','',7, now(), now() );


