INSERT INTO `mr_characters` VALUES (1,'id',1,9,1, 23,now(), now() ),
                                   (2, 'abundance', 2, 1, 9,  5,now(), now() ),            -- lookup in lookup_items
                                   (3,'mushroom_age',2,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (4,'odor',2,1,9, 5, now(), now() ),                 -- lookup in lookup_items
                                   (5,'taste',2,1,9, 5, now(), now() ),                 -- lookup in lookup_items
                                   (6,'toxic',2,1,9, 5, now(), now() ),                 -- lookup in lookup_items
                                   (7,'habit',2,1,11, 5, now(), now() ),                 -- lookup in lookup_items
                                   (8,'pileus_width',3,1,2, 5, now(), now() ),
                                   (9,'pileus_height',3,1,2, 5, now(), now() ),
                                   (10,'pileus_shape',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (11,'pileus_shape_top_views',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (12,'pileus_color',3,1,6, 5, now(), now() ),
                                   (13,'pileus_color_disc',3,1,6, 5, now(), now() ),
                                   (14,'pileus_color_margin',3,1,6, 5, now(), now() ),
                                   (15,'pileus_color_background',3,1,6, 5, now(), now() ),
                                   (16,'pileus_color_fibrils',3,1,6, 5, now(), now() ),
                                   (17,'pileus_color_bruised',3,1,6, 5, now(), now() ),
                                   (18,'pileus_color_wet',3,1,6, 5, now(), now() ),
                                   (19,'pileus_color_dry',3,1,6, 5, now(), now() ),
                                   (20,'pileus_surface_dryness',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (21,'pileus_surface_texture_mrdbid',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (22,'pileus_margin_shape',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (23,'pileus_margin_type',3,1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (24,'pileus_hairy_y_n',3,1,5, 5, now(), now() ),
                                   (25,'pileus_context_flesh_color_moist',3,1,6, 5, now(), now() ),
                                   (26,'pileus_context_flesh_color_dry',3,1,6, 5, now(), now() ),
                                   (27,'pileus_context_flesh_color_cuticle',3,1,6, 5, now(), now() ),
                                   (28,'pileus_context_flesh_thickness_disc',3,1, 2, 5,now(), now() ),
                                   (29,'pileus_context_flesh_thickness_margin',3,1,2, 1, now(), now() ),
                                   (30,'pileus_context_flesh_texture',3,1,3, 9, now(), now() ),             -- lookup in lookup_items
                                   (31,'pileus_context_flesh_latex_color',3,1,6, 1, now(), now() ),
                                   (32,'pileus_context_flesh_latex_color_exposed',3,1,6, 1, now(), now() ),
                                   (33,'pileus_context_flesh_latex_taste',3,1,7, 1, now(), now() ),
                                   (34,'pileus_context_flesh_latex_abundance',3,1,5, 1, now(), now() ),
                                   (35,'lamella_attachment',4, 1,9, 5, now(), now() ),             -- lookup in lookup_items
                                   (36,'lamella_breadth',4,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (37,'lamella_thickness',4,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (38,'lamella_spacing',4,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (39,'lamella_color_young',4,1,6, 1, now(), now() ),
                                   (40,'lamella_color_mature',4,1,6, 1, now(), now() ),
                                   (41,'lamella_edge',4,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (42,'lamella_misc_waxy_y_n',4,1,5, 1, now(), now() ),
                                   (43,'lamella_misc_arid_dry_y_n',4,1,5, 1, now(), now() ),
                                   (44,'lamella_misc_deliquescent_y_n',4,1,5, 1, now(), now() ),
                                   (45,'stipe_location',5,1,5, 5, now(), now() ),
                                   (46,'stipe_height',5,1,2, 5, now(), now() ),
                                   (47,'stipe_diameter_top',5,1,4, 1, now(), now() ),
                                   (48,'stipe_diameter_mid',5,1,4, 1, now(), now() ),
                                   (49,'stipe_diameter_low',5,1,4, 1, now(), now() ),
                                   (50,'stipe_shape',5,1,9, 1, now(), now() ),              -- lookup in lookup_items
                                   (51,'stipe_color',5,1,6, 1, now(), now() ),
                                   (52,'stipe_color_change',5,1,6, 1, now(), now() ),
                                   (53,'stipe_color_base',5,1,6, 1, now(), now() ),
                                   (54,'stipe_color_apex',5,1,6, 1, now(), now() ),
                                   (55,'stipe_color_interior',5,1,6, 1, now(), now() ),
                                   (56,'stipe_color_exterior',5,1,6, 1, now(), now() ),
                                   (57,'stipe_color_bruise',5,1,6, 1, now(), now() ),
                                   (58,'stipe_surface',5,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (59,'stipe_texture',5,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (60,'stipe_interior_mrdbid',5,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (61,'partial_inner_veil_annular_ring_position',6,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (62,'veil_annulus',6,1,5, 1, now(), now() ),
                                   (63,'partial_inner_veil_color',6,1,6, 1, now(), now() ),
                                   (64,'partial_inner_veil_texture',6,1,6, 1, now(), now() ),             -- lookup in lookup_items
                                   (65,'partial_inner_veil_fate',6,1,6, 1, now(), now() ),             -- lookup in lookup_items
                                   (66,'partial_inner_veil_annular_ring',6,1,5, 1, now(), now() ),
                                   (67,'partial_inner_veil_appearance',6,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (68,'universal_outer_veil_description',6,1,5, 1, now(), now() ),
                                   (69,'universal_outer_veil_volva',6,1,5, 1, now(), now() ),
                                   (70,'bulb_type',2,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (71,'mycelium_color',14,1,6, 1, now(), now() ),
                                   (72,'mycelium_texture',7,1,9, 1, now(), now() ),
                                   (73,'spore_color',14,1,6, 1, now(), now() ),
                                   (74,'spore_range_low',8,1,2, 1, now(), now() ),
                                   (75,'spore_range_high',8,1,2, 1, now(), now() ),
                                   (76,'habitat',11,1,5, 1, now(), now() ),             -- lookup in lookup_items
                                   (77,'soil_type',11,1,5, 1, now(), now() ),             -- lookup in lookup_items
                                   (78,'soil_temp',11,1,5, 1, now(), now() ),
                                   (79,'air_temp',11,1,5, 1, now(), now() ),
                                   (80,'plant_association',11,1,5, 1, now(), now() ),
                                   (81,'rhizomorph_color',463,1,6, 1, now(), now() ),
                                   (82,'rhizomorph_texture',463,1,5, 1, now(), now() ),
                                   (83,'chem_reaction',9,1,5, 1, now(), now() ),             -- lookup in lookup_items
                                   (84,'weight_before_dry',2,1,4, 1, now(), now() ),
                                   (85,'weight_after_dry',2,1,4, 1, now(), now() ),
                                   (86,'elevation',11,1,4, 1, now(), now() ),
                                   (87,'soil_ph',11,1,4, 1, now(), now() ),
                                   (88,'stipe_latex_color_exposed',5,1,6, 1, now(), now() ),
                                   (89,'stipe_latex_taste',5,1,5, 1, now(), now() ),
                                   (90,'stipe_latex_abundance',5,1,5, 1, now(), now() ),
                                   (91,'mycobank_name',16,1,5, 1, now(), now() ),
                                   (92,'inaturalist_num',16,1,5, 1, now(), now() ),
                                   (93,'mushroom_observer_num',16,1,5, 1, now(), now() ),
                                   (94,'location_found_latitude',15,1,4, 1, now(), now() ),
                                   (95,'location_found_longitude',15,1,4, 1, now(), now() ),
                                   (96,'project_belong_to',2,1,5, 1, now(), now() ),
                                   (97,'microscope_slides_included',2,1,5, 1, now(), now() ),
                                   (98,'preservation_method',2,1,5, 1, now(), now() ),
                                   (99,'annulus_position',2,9,5,1, now(), now() ),                   -- lookup in lookup_items
                                   (100,'mushroom_storage_location',467,1,9, 1, now(), now() ),             -- lookup in lookup_items
                                   (101,'countries',15,1,11, 1, now(), now() ),                      -- lookup in lookup_items
                                   (102,'states',15,1,12, 1, now(), now() ),
                                   (105,'fungus_types',2,1,9, 1, now(), now()),                    -- lookup in lookup_items
                                   (106,'universal_outer_veil_appearances',6,1,9, 1, now(), now()),             -- lookup in lookup_items
                                   (107,'universal_outer_veil_fates',6,1,9, 1, now(), now()),             -- lookup in lookup_items
                                   (108,'universal_outer_veil_textures',6,1,9, 1, now(), now()),             -- lookup in lookup_items
                                   (109,'veils',6,6,9, 1, now(), now()),                           -- lookup in lookup_items
                                   (110,'synonyms',1,451,9, 1, now(), now()),                         -- lookup in lookup_items
                                   (112,'pileus_shape_form',3,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (113,'pileus_height_mm',3,1,2,44,now(),now() ),
                                   (114,'pileus_width_mm',3,1,2,44,now(),now() ),
                                   (115,'pileus_tissue_thickness_mm',3,1,2,44,now(),now() ),
                                   (116,'pileus_color_spectrum',3,1,6,44,now(),now() ),
                                   (117,'pilei_surface_wetness',3,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (118,'pileus_hygrophanous_or_non',3,1,5,44,now(),now() ),
                                   (119,'pileus_striate_or_not',3,1,5,44,now(),now() ),
                                   (120,'pileus_center',3,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (121,'pileus_central_disc_colored',3,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (122,'pileus_pellicle_gelatinous_separable',3,1,5,44,now(),now() ),
                                   (123,'pilei_surface_shininess_or_non',3,1,5,44,now(),now() ),
                                   (124,'pileus_surface_texture',3,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (125,'pileus_margin_form',3,1,5,44,now(),now() ),
                                   (126,'pileus_margin_smooth_cleft_in_turn',3,1,5,44,now(),now() ),
                                   (127,'pileus_veil_flocks_adhere_pileus_margin',3,1,5,44,now(),now() ),
                                   (128,'pilei_striations_length_mm',3,1,2,44,now(),now() ),
                                   (129,'pilei_striations_width_mm',3,1,2,44,now(),now() ),
                                   (130,'pilei_striations_depth_mm',3,1,2,44,now(),now() ),
                                   (131,'pilei_striations_frequency',3,1,5,44,now(),now() ),
                                   (132,'pilei_striations_countenance',3,1,5,44,now(),now() ),
                                   (133,'pileus_cuticle_removes_easily',3,1,5,44,now(),now() ),
                                   (134,'pileus_radial_furrows_present',3,1,5,44,now(),now() ),
                                   (135,'pileus_stem_clean_separation',3,1,5,44,now(),now() ),
                                   (136,'pileus_spore_deposits_resting_on_pileus_surface_color',3,1,6,44,now(),now() ),
                                   (137,'pileus_response_knife_streak',3,1,5,44,now(),now() ),
                                   (138,'pilei_zonate_pattern',3,1,5,44,now(),now() ),
                                   (139,'pileus_rolled_up_presence_reveals_lamellaes_curled_up',3,1,5,44,now(),now() ),
                                   (140,'lamellae_color',4,1,6,44,now(),now() ),
                                   (141,'lamellae_color_change_sterile_to_young',4,1,5,44,now(),now() ),
                                   (142,'lamellae_color_change_to_mature_lamellae',4,1,5,44,now(),now() ),
                                   (143,'lamellae_distance_spacing',4,1,9,44,now(),now() ),                                    -- lookup in lookup_items
                                   (144,'lamellae_thickness',4,1,9,44,now(),now() ),                              -- lookup in lookup_items
                                   (145,'lamellae_blade_breadth',4,1,9,44,now(),now() ),                                      -- lookup in lookup_items
                                   (146,'lamellae_edges_exhibit_gelantinour_pallid_thickish_thread ',4,1,5,44,now(),now() ),
                                   (147,'lamellae_attachment',4,1,9,44,now(),now() ),                                         -- lookup in lookup_items
                                   (148,'lamellae_spore_print_colors',4,1,6,44,now(),now() ),
                                   (149,'lamellae_spore_print_deposit_heaviness',4,1,5,44,now(),now() ),
                                   (150,'lamellae_permanently_sterile',4,1,5,44,now(),now() ),
                                   (151,'lamellae_nearly_sterile',4,1,5,44,now(),now() ),
                                   (152,'lamellae_anastomosing_present',4,1,5,44,now(),now() ),
                                   (153,'lamellae_false_present',4,1,5,44,now(),now() ),
                                   (154,'lamellae_lamellula_present',4,1,5,44,now(),now() ),
                                   (155,'lamellae_position_above_view',4,1,5,44,now(),now() ),
                                   (156,'lamellae_forking_branching',4,1,5,44,now(),now() ),
                                   (157,'lamellae_mottled_present',4,1,5,44,now(),now() ),
                                   (158,'lamellae_margin_nuanced_color_due_cheilocystidia',4,1,5,44,now(),now() ),
                                   (159,'lamellae_margins_nuanced_texture_appearance',4,1,9,44,now(),now() ),             -- lookup in lookup_items
                                   (160,'lamellae_wavy',4,1,5,44,now(),now() ),
                                   (161,'lamellae_knife_cut_response',4,1,5,44,now(),now() ),
                                   (162,'lamellae_veil_fragments_adhere',4,1,5,44,now(),now() ),
                                   (163,'lamellae_lamellar_edge_partially_completely_pigmented_edges_not_cystidia_appearance_result',4,1,5,44,now(),now() ),
                                   (164,'stipe_veil_or_cortina_present',5,1,5,44,now(),now() ),
                                   (165,'stipe_annulus_or_annular_zone_present',5,1,5,44,now(),now() ),
                                   (166,'stipe_annulus_scar_from_once_present_annulus',5,1,5,44,now(),now() ),
                                   (167,'stipe_annulus_easily_removed_or_falls_off_stem',5,1,5,44,now(),now() ),
                                   (168,'stipe_annulus_ridge_present',5,1,5,44,now(),now() ),
                                   (169,'stipe_length_mm',5,1,2,44,now(),now() ),
                                   (170,'stipe_width_mm',5,1,2,44,now(),now() ),
                                   (171,'stipe_bulbous_base_diameter_mm',5,1,2,44,now(),now() ),
                                   (172,'stipe_bulbous_base_height_mm',5,1,2,44,now(),now() ),
                                   (173,'stipe_colors',5,1,6,44,now(),now() ),
                                   (174,'stipe_surface_texture',5,1,9,44,now(),now() ),                                  -- lookup in lookup_items
                                   (175,'stipe_apex_has_striations',5,1,5,44,now(),now() ),
                                   (176,'stipe_color_spectrum',5,1,6,44,now(),now() ),
                                   (177,'stipe_interior',5,1,9,44,now(),now() ),                                 -- lookup in lookup_items
                                   (178,'stipe_vertical_fold_present',5,1,5,44,now(),now() ),
                                   (179,'stipe_rhizomorphs_present_at_base',5,1,5,44,now(),now() ),
                                   (180,'stipe_mycelium_present_at_base',5,1,5,44,now(),now() ),
                                   (181,'stipe_pseudorhiza_present',5,1,5,44,now(),now() ),
                                   (182,'stipe_base_shape',5,1,5,44,now(),now() ),
                                   (183,'stipe_base_color',5,1,6,44,now(),now() ),
                                   (184,'stipe_base_width_mm',5,1,2,44,now(),now() ),
                                   (185,'stipe_base_height_mm',5,1,2,44,now(),now() ),
                                   (186,'stipe_base_attachment',5,1,5,44,now(),now() ),
                                   (187,'stipe_basal_disc_present',5,1,5,44,now(),now() ),
                                   (188,'stipe_radicating_or_non',5,1,5,44,now(),now() ),
                                   (189,'stipe_basal_mycelium_form',111,1,5,44,now(),now() ),
                                   (190,'stipe_basal_mycelium_color',111,1,6,44,now(),now() ),
                                   (191,'stipe_basal_mycelium_width_mm',5,1,2,44,now(),now() ),
                                   (192,'stipe_basal_mycelium_length_mm',5,1,2,44,now(),now() ),
                                   (193,'stipe_basal_mycelium_density',5,1,5,44,now(),now() ),
                                   (194,'stipe_basal_mycelium_substrate_attachment',5,1,5,44,now(),now() ),
                                   (195,'stipe_basal_mycelium_cell_amiloidity',5,1,5,44,now(),now() ),
                                   (196,'substrata_items_still_attached_to_basidiocarp_base_upon_harvesting',5,1,5,44,now(),now() ),
                                   (197,'stipe_pattern_appearance_consistency',5,1,5,44,now(),now() ),
                                   (198,'stipe_form',5,1,5,44,now(),now() ),                                                      -- lookup in lookup_items
                                   (199,'stipe_base_nuance_contrast',5,1,5,44,now(),now() ),
                                   (200,'stipe_base_striations',5,1,5,44,now(),now() ),
                                   (201,'stipe_base_striation_length_mm',5,1,2,44,now(),now() ),
                                   (202,'stipe_base_striation_width_mm',5,1,2,44,now(),now() ),
                                   (203,'stipe_base_striation_depth_mm',5,1,2,44,now(),now() ),
                                   (204,'stipe_base_striation_frequency',5,1,5,44,now(),now() ),
                                   (205,'stipe_strict_or_relaxed_longitudinal_lines',5,1,5,44,now(),now() ),
                                   (206,'stipe_line_patterns',5,1,5,44,now(),now() ),
                                   (207,'stipe_volva_present_observable_attributes',5,1,5,44,now(),now() ),
                                   (208,'stipe_volva_height_mm',5,1,2,44,now(),now() ),
                                   (209,'stipe_volva_present  ',5,1,5,44,now(),now() ),
                                   (210,'stipe_volva_evanescence',5,1,5,44,now(),now() ),
                                   (211,'stipe_volva_persistence',5,1,5,44,now(),now() ),
                                   (212,'stipe_volva_pseudovolva_present',5,1,5,44,now(),now() ),
                                   (213,'stipe_volva_sack_elongated_tubular_present',5,1,5,44,now(),now() ),
                                   (214,'stipe_volva_marginate_bulb_present',5,1,5,44,now(),now() ),
                                   (215,'stipe_volva_oxonium_present',5,1,5,44,now(),now() ),
                                   (216,'stipe_surface_tissue_peeling_up_or_down',5,1,5,44,now(),now() ),
                                   (217,'stipe_veil_flocks_adhere_stipe',5,1,5,44,now(),now() ),
                                   (218,'stipe_easily_fractures_when_bent',5,1,5,44,now(),now() ),
                                   (219,'stipe_surface_spore_deposit_color',5,1,6,44,now(),now() ),
                                   (220,'stipe_pothole_like_depression',5,1,5,44,now(),now() ),
                                   (221,'stipe_annulus_persistent',5,1,5,44,now(),now() ),
                                   (222,'stipe_surface_exhibits_cottony_hyphal_appearance',5,1,5,44,now(),now() ),
                                   (223,'stipe_mycelium_growing_up_base_and_up_stem',5,1,5,44,now(),now() ),
                                   (224,'stipe_tapered_upward_or_downward',5,1,5,44,now(),now() ),
                                   (225,'stipe_internal_necrosis_present',5,1,5,44,now(),now() ),
                                   (226,'stipe_annulus_height_in_relation_to_stipe',5,1,5,44,now(),now() ),
                                   (227,'stipe_knife_cut_response',5,1,5,44,now(),now() ),
                                   (228,'stipe_exhibits_noteworthy_elevated_striations',5,1,5,44,now(),now() ),
                                   (229,'fruiting_body_entire_height',2,1,2,44,now(),now() ),
                                   (230,'growth_stage_video',2,1,5,44,now(),now() ),
                                   (231,'habitat_EXD',11,1,5,44,now(),now() ),
                                   (232,'ecology',11,1,5,44,now(),now() ),
                                   (233,'substrate',11,1,5,44,now(),now() ),
                                   (234,'substrata',11,1,9,44,now(),now() ),                            -- lookup in lookup_items
                                   (235,'trees_present',11,1,5,44,now(),now() ),
                                   (236,'nutrition_mode',2,1,9,44,now(),now() ),                         -- lookup in lookup_items
                                   (237,'mycorrhizal_relationships',11,1,5,44,now(),now() ),
                                   (238,'plant_relationships',11,1,5,44,now(),now() ),
                                   (239,'nutrition_mode_change',2,1,5,44,now(),now() ),
                                   (240,'locality',15,1,5,44,now(),now() ),
                                   (241,'geographic_distribution',15,1,5,44,now(),now() ),
                                   (242,'latitude_EXD',15,1,4,44,now(),now() ),
                                   (243,'longitude_EXD',15,1,4,44,now(),now() ),
                                   (244,'fruiting_body_entire_weight',2,1,4,44,now(),now() ),
                                   (245,'natural_fruiting_time_of_year',2,1,5,44,now(),now() ),
                                   (246,'sclerotia_pseudosclerotia_present', 460,1,5,44,now(),now() ),
                                   (247,'primordia_form',2,1,5,44,now(),now() ),
                                   (248,'primordia_colors',2,1,6,44,now(),now() ),
                                   (249,'growth_pattern_general',2,1,5,44,now(),now() ),
                                   (250,'field_chemical_reaction_test',9,1,5,44,now(),now() ),
                                   (251,'aroma',2,1,5,44,now(),now() ),
                                   (252,'flavor',2,1,5,44,now(),now() ),
                                   (253,'universal_veil_present',6,1,5,44,now(),now() ),
                                   (254,'universal_veil_remnants_warts_present',6,1,5,44,now(),now() ),
                                   (255,'deliquesence_present',2,1,5,44,now(),now() ),
                                   (256,'lactiferous_fluid_present',2,1,5,44,now(),now() ),
                                   (257,'transient_morphing_ephemeral_characters_during_growth_stages',2,1,5,44,now(),now() ),
                                   (258,'stature_types',2,1,5,44,now(),now() ),
                                   (259,'basidiocarps_fragile_normal_tough',2,1,9,44,now(),now() ),                      -- lookup in lookup_items
                                   (260,'handling_specimen_color_change',2,1,9,44,now(),now() ),                       -- lookup in lookup_items
                                   (261,'photographic_compare_fresh',2,1,5,44,now(),now() ),
                                   (262,'photograph_compare_dried_completely_dehydrated',2,1,5,44,now(),now() ),
                                   (263,'pileus_compare_color_spectrum_very_moist_rainy',3,1,6,44,now(),now() ),
                                   (264,'pileus_compare_color_spectrum_non_rainy',3,1,6,44,now(),now() ),
                                   (265,'stipe_compare_color_spectrum_very_moist_rainy',5,1,6,44,now(),now() ),
                                   (266,'stipe_compare_color_spectrum_non_rainy',5,1,6,44,now(),now() ),
                                   (267,'fluorescent_reaction_ultraviolent_light_present',2,1,5,44,now(),now() ),
                                   (268,'bioluminescence',2,1,5,44,now(),now() ),
                                   (269,'pilei_exhibit_darkening_burn_like_character',3,1,5,44,now(),now() ),
                                   (270,'stipe_exhibit_darkening_burn_like_character',3,1,5,44,now(),now() ),
                                   (271,'time_from_primordia_to_decompose',2,1,5,44,now(),now() ),
                                   (272,'elevation_EXD',15,1,4,44,now(),now() ),
                                   (273,'survive_completely_aquatic_environment',2,1,5,44,now(),now() ),
                                   (274,'survive_snowpack_melt_mountains',2,1,5,44,now(),now() ),
                                   (275,'survive_fire_burn',2,1,5,44,now(),now() ),
                                   (276,'fruiting_temperature_low',11,1,4,44,now(),now() ),
                                   (277,'fruiting_temperature_high',11,1,4,44,now(),now() ),
                                   (278,'fruiting_humidity_low',11,1,4,44,now(),now() ),
                                   (279,'fruiting_humidity_high',11,1,4,44,now(),now() ),
                                   (280,'grow_light_uv_spectrum_response',2,1,5,44,now(),now() ),
                                   (281,'deep_low_sounding_audio_waves_during_growth_response',2,1,5,44,now(),now() ),
                                   (282,'albinistic_leucistic_fruit_body_presence',2,1,5,44,now(),now() ),
                                   (283,'secotioid_formation_present',2,1,5,44,now(),now() ),
                                   (284,'mycelium_strongly_present_above_substrate_surface',2,1,5,44,now(),now() ),
                                   (285,'aborts_pins_present',2,1,5,44,now(),now() ),
                                   (286,'pileus_guttation_drops_present',3,1,5,44,now(),now() ),
                                   (287,'stipe_guttation_drops_present',5,1,5,44,now(),now() ),
                                   (288,'lamellaes_guttation_drops_present',4,1,5,44,now(),now() ),
                                   (289,'pileus_guttation_drops_color',3,1,6,44,now(),now() ),
                                   (290,'stipe_guttation_drops_color',5,1,6,44,now(),now() ),
                                   (291,'lamellaes_guttation_drops_color',4,1,6,44,now(),now() ),
                                   (292,'pileus_guttation_drops_abundance',3,1,5,44,now(),now() ),
                                   (293,'stipe_guttation_drops_abundance',5,1,5,44,now(),now() ),
                                   (294,'lamellaes_guttation_drops_abundance',4,1,5,44,now(),now() ),
                                   (295,'agaricicolous_growing_on_other_fungus',2,1,5,44,now(),now() ),
                                   (296,'polymorphic',2,1,5,44,now(),now() ),
                                   (297,'fungal_dysmorphias_present',2,1,5,44,now(),now() ),
                                   (298,'veil_thickness',6,1,5,44,now(),now() ),
                                   (299,'veil_relative_strength',6,1,5,44,now(),now() ),
                                   (300,'veil_overall_lifespan_developments',6,1,5,44,now(),now() ),
                                   (301,'common_or_rare',2,1,5,44,now(),now() ),
                                   (302,'how_fleshy_freshly_harvested',2,1,5,44,now(),now() ),
                                   (303,'water_spots_present',2,1,5,44,now(),now() ),
                                   (304,'colors_present',2,2,6,44,now(),now() ),
                                   (305,'setae_present',2,2,5,44,now(),now() ),
                                   (306,'automate_micaceous_structures',2,2,5,44,now(),now() ),
                                   (307,'color_reaction_nh4oh',9,3,5,44,now(),now() ),
                                   (308,'color_reaction_koh',9,3,5,44,now(),now() ),
                                   (309,'color_reaction_feso4',9,3,5,44,now(),now() ),
                                   (310,'color_reaction_pdab',9,3,5,44,now(),now() ),
                                   (311,'color_reaction_phenol',9,3,5,44,now(),now() ),
                                   (312,'color_reaction_schaeffer',9,3,5,44,now(),now() ),
                                   (313,'color_reaction_guiac',9,3,5,44,now(),now() ),
                                   (314,'color_reaction_weiland_meixner',9,3,5,44,now(),now() ),
                                   (315,'color_reaction_sulfovanillin',9,3,5,44,now(),now() ),
                                   (316,'aroma_XDE',2,1,5,44,now(),now() ),                                -- lookup in lookup_items
                                   (317,'taste_XDE',2,1,5,44,now(),now() ),
                                   (318,'pileus_trama_pattern',3,4,5,44,now(),now() ),
                                   (319,'pileus_pileipellis_pattern',3,4,5,44,now(),now() ),             -- lookup in lookup_items
                                   (320,'pilei_cystidia_present',3,4,5,44,now(),now() ),
                                   (321,'pelei_cystidia_size',3,4,5,44,now(),now() ),
                                   (322,'pelei_cystidia_form',3,4,5,44,now(),now() ),
                                   (323,'pileipellis_end_hyphae_present',3,4,5,44,now(),now() ),
                                   (324,'pileocystidia_present',3,4,5,44,now(),now() ),
                                   (325,'setae_present_2',3,4,5,44,now(),now() ),
                                   (326,'circumcystidia_present',3,4,5,44,now(),now() ),
                                   (327,'pileipellis_end_hyphae_measurement',3,4,5,44,now(),now() ),
                                   (328,'pileocystidia_measurement',3,4,5,44,now(),now() ),
                                   (329,'setae_measurement',2,4,5,44,now(),now() ),
                                   (330,'circumcystidia_measurement',2,4,5,44,now(),now() ),
                                   (331,'circumcystidia_form_1',2,4,5,44,now(),now() ),
                                   (332,'circumcystidia_form_2',2,4,5,44,now(),now() ),
                                   (333,'circumcystidia_form_3',2,4,5,44,now(),now() ),
                                   (334,'circumcystidia_form_4',2,4,5,44,now(),now() ),
                                   (335,'clamp_connection_present',2,4,5,44,now(),now() ),
                                   (336,'pileipellis_exhibits_encrusted_pigments',2,4,5,44,now(),now() ),
                                   (337,'broom_cells_observed_in_pileipellis',2,4,5,44,now(),now() ),
                                   (338,'apical_projections_observed_in_pileipellis',2,4,5,44,now(),now() ),
                                   (339,'velipellis_present',2,4,5,44,now(),now() ),
                                   (340,'lamellae_spore_width_nm',8,4,5,44,now(),now() ),
                                   (341,'lamellae_spore_height_nm',8,4,5,44,now(),now() ),
                                   (342,'lamellae_spore_width_max_nm',8,4,5,44,now(),now() ),
                                   (343,'lamellae_spore_width_min_nm',8,4,5,44,now(),now() ),
                                   (344,'lamellae_spore_height_max_nm',8,4,5,44,now(),now() ),
                                   (345,'lamellae_spore_height_min_nm',8,4,5,44,now(),now() ),
                                   (346,'lamellae_spore_shape',8,4,5,44,now(),now() ),
                                   (347,'lamellae_spore_wall_thickness_nm',8,4,5,44,now(),now() ),
                                   (348,'lamellae_spore_color',8,4,5,44,now(),now() ),
                                   (349,'lamellae_spore_ornamentation',8,4,5,44,now(),now() ),
                                   (350,'lamellae_spore_germ_pore_present',8,4,5,44,now(),now() ),
                                   (351,'lamellae_spore_symmetry',8,4,5,44,now(),now() ),
                                   (352,'lamellae_spore_attachment',8,4,5,44,now(),now() ),
                                   (353,'lamellae_spore_membrane_perispore_present',8,4,5,44,now(),now() ),
                                   (354,'lamellae_spore_pigmentation_test',8,4,5,44,now(),now() ),
                                   (355,'lamellae_spore_inner_contents',8,4,5,44,now(),now() ),
                                   (356,'lamellae_cheilocystidia_present',4,4,5,44,now(),now() ),
                                   (357,'lamellae_cheilocystidia_width',4,4,5,44,now(),now() ),
                                   (358,'lamellae_cheilocystidia_height',4,4,5,44,now(),now() ),
                                   (359,'lamellae_cheilocystidia_shape',4,4,5,44,now(),now() ),
                                   (360,'lamellae_cheilocystidia_color',4,4,5,44,now(),now() ),
                                   (361,'lamellae_cheilocystidia_ornamentation',4,4,5,44,now(),now() ),
                                   (362,'lamellae_cheilocystidia_crystals_present',4,4,5,44,now(),now() ),
                                   (363,'lamellae_cheilocystidia_encrustation',4,4,5,44,now(),now() ),
                                   (364,'lamellae_cheilocystidia_wall_thickness',4,4,5,44,now(),now() ),
                                   (365,'lamellae_cheilocystidia_individual_variation',4,4,5,44,now(),now() ),
                                   (366,'lamellae_cheilocystidia_contents',4,4,5,44,now(),now() ),
                                   (367,'lamellae_pleurocystidia_present',4,4,5,44,now(),now() ),
                                   (368,'lamellae_pleurocystidia_width',4,4,5,44,now(),now() ),
                                   (369,'lamellae_pleurocystidia_height',4,4,5,44,now(),now() ),
                                   (370,'lamellae_pleurocystidia_shape',4,4,5,44,now(),now() ),
                                   (371,'lamellae_pleurocystidia_color',4,4,5,44,now(),now() ),
                                   (372,'lamellae_pleurocystidia_ornamentation',4,4,5,44,now(),now() ),
                                   (373,'lamellae_pleurocystidia_crystals_present',4,4,5,44,now(),now() ),
                                   (374,'lamellae_pleurocystidia_encrustation',4,4,5,44,now(),now() ),
                                   (375,'lamellae_pleurocystidia_wall_thickness',4,4,5,44,now(),now() ),
                                   (376,'lamellae_pleurocystidia_individual_variation',4,4,5,44,now(),now() ),
                                   (377,'lamellae_pleurocystidia_contents',4,4,5,44,now(),now() ),
                                   (378,'lamellae_other_types_cystidia_present',4,4,5,44,now(),now() ),
                                   (379,'lamellae_other_types_cystidia_form',4,4,5,44,now(),now() ),
                                   (380,'lamellae_other_types_cystidia_width',4,4,5,44,now(),now() ),
                                   (381,'lamellae_other_types_cystidia_height',4,4,5,44,now(),now() ),
                                   (382,'lamellae_other_types_cystidia_capitula_width',4,4,5,44,now(),now() ),
                                   (383,'lamellae_basidia_width',4,4,5,44,now(),now() ),
                                   (384,'lamellae_basidia_height',4,4,5,44,now(),now() ),
                                   (385,'lamellae_basidia_appearance_variation',4,4,5,44,now(),now() ),
                                   (386,'lamellae_basidia_sterigmata_amount',4,4,5,44,now(),now() ),
                                   (387,'lamellae_lamellae_trama_pattern',4,4,5,44,now(),now() ),               -- lookup in lookup_items
                                   (388,'lamellae_subhymenium_pattern_type',4,4,5,44,now(),now() ),
                                   (389,'lamellae_droplets_quttules_within_spore_present',4,4,5,44,now(),now() ),
                                   (390,'lamellae_droplets_quttules_within_spore_quantity',4,4,5,44,now(),now() ),
                                   (391,'lamellae_paracystidia_present',4,4,5,44,now(),now() ),
                                   (392,'lamellae_carminophilous_basidia_present',4,4,5,44,now(),now() ),
                                   (393,'lamellae_metachromatic_color_reaction_to_spore_wall_present',4,4,5,44,now(),now() ),
                                   (394,'lamellae_coscinocystidia_present',4,4,5,44,now(),now() ),
                                   (395,'lamellae_macrocystidia_present',4,4,5,44,now(),now() ),
                                   (396,'stipe_trama',5,4,5,44,now(),now() ),
                                   (397,'stipe_stipitipellis_form',5,4,5,44,now(),now() ),
                                   (398,'stipe_cystidia_present',5,4,5,44,now(),now() ),
                                   (399,'stipe_cystidia_width',5,4,5,44,now(),now() ),
                                   (400,'stipe_cystidia_height',5,4,5,44,now(),now() ),
                                   (401,'stipe_form_2',5,4,5,44,now(),now() ),
                                   (402,'stipe_palisade_present',5,4,5,44,now(),now() ),
                                   (403,'stipe_more_characters_pileus_cystidia_present',5,4,5,44,now(),now() ),
                                   (404,'stipe_more_characters_pileus_cystidia_form',5,4,5,44,now(),now() ),
                                   (405,'stipe_more_characters_pileus_cystidia_width',5,4,5,44,now(),now() ),
                                   (406,'stipe_more_characters_pileus_cystidia_height',5,4,5,44,now(),now() ),
                                   (407,'stipe_more_characters_caulocystidia_present',5,4,5,44,now(),now() ),
                                   (408,'stipe_more_characters_caulocystidia_form',5,4,5,44,now(),now() ),
                                   (409,'stipe_more_characters_caulocystidia_width',5,4,5,44,now(),now() ),
                                   (410,'stipe_more_characters_caulocystidia_height',5,4,5,44,now(),now() ),
                                   (411,'stipe_more_characters_chrysocystidia_present',5,4,5,44,now(),now() ),
                                   (412,'stipe_more_characters_chrysocystidia_form',5,4,5,44,now(),now() ),
                                   (413,'stipe_more_characters_chrysocystidia_width',5,4,5,44,now(),now() ),
                                   (414,'stipe_more_characters_chrysocystidia_height',5,4,5,44,now(),now() ),
                                   (415,'stipe_more_characters_mycelia_cystidia_present',5,4,5,44,now(),now() ),
                                   (416,'stipe_more_characters_mycelia_cystidia_form',5,4,5,44,now(),now() ),
                                   (417,'stipe_more_characters_mycelia_cystidia_width',5,4,5,44,now(),now() ),
                                   (418,'stipe_more_characters_mycelia_cystidia_height',5,4,5,44,now(),now() ),
                                   (419,'stipe_more_characters_brachycystidia_present',5,4,5,44,now(),now() ),
                                   (420,'stipe_more_characters_brachycystidia_form',5,4,5,44,now(),now() ),
                                   (421,'stipe_more_characters_brachycystidia_width',5,4,5,44,now(),now() ),
                                   (422,'stipe_more_characters_brachycystidia_height',5,4,5,44,now(),now() ),
                                   (423,'stipe_more_characters_lamprocystidia_present',5,4,5,44,now(),now() ),
                                   (424,'stipe_more_characters_lamprocystidia_form',5,4,5,44,now(),now() ),
                                   (425,'stipe_more_characters_lamprocystidia_width',5,4,5,44,now(),now() ),
                                   (426,'stipe_more_characters_lamprocystidia_height',5,4,5,44,now(),now() ),
                                   (427,'stipe_more_characters_mycelial_conidia',5,4,5,44,now(),now() ),
                                   (428,'stipe_more_characters_sclerotia_layers',5,4,5,44,now(),now() ),
                                   (429,'stipe_more_characters_sclerotia_hyphae_appearance',5,4,5,44,now(),now() ),
                                   (430,'stipe_more_characters_cell_chemical_reaction_test_koh',5,4,5,44,now(),now() ),
                                   (431,'stipe_more_characters_cell_chemical_reaction_test_lugols',5,4,5,44,now(),now() ),
                                   (432,'stipe_more_characters_cell_chemical_reaction_test_sulfuric_acid',5,4,5,44,now(),now() ),
                                   (433,'stipe_more_characters_melzers',5,4,5,44,now(),now() ),
                                   (434,'stipe_more_characters_clamp_connection_present',5,4,5,44,now(),now() ),
                                   (435,'stipe_more_characters_setae_present_3',5,4,5,44,now(),now() ),
                                   (436,'stipe_more_characters_acanthocytesPresent',5,4,5,44,now(),now() ),
                                   (437,'stipe_more_characters_basal_mycelium_crystals_present',5,4,5,44,now(),now() ),
                                   (438,'stipe_more_characters_spores_exhibit_calyptration',5,4,5,44,now(),now() ),
                                   (439,'stipe_more_characters_spores_exterior_exhibits_covering',5,4,5,44,now(),now() ),
                                   (440,'stipe_more_characters_refractive_content_present',5,4,5,44,now(),now() ),
                                   (441,'chemical_tests_sulfovanillin',9,4,5,44,now(),now() ),
                                   (442,'chemical_tests_melzers',9,4,5,44,now(),now() ),
                                   (443,'psilocybin_present',9,5,5,44,now(),now() ),
                                   (444,'psilocybin_quantity',9,5,5,44,now(),now() ),
                                   (445,'psilocin_present',9,5,5,44,now(),now() ),
                                   (446,'psilocin_quantity',9,5,5,44,now(),now() ),
                                   (447,'cyanescin_present',9,5,5,44,now(),now() ),
                                   (448,'cyanescin_quantity',9,5,5,44,now(),now() ),
                                   (449,'nor_cyanescin_present',9,5,5,44,now(),now() ),
                                   (450,'nor_cyanescin_quantity',9,5,5,44,now(),now() ),
                                   (451,'aeruginascin_present',9,5,5,44,now(),now() ),
                                   (452,'aeruginascin_quantity',9,5,5,44,now(),now() ),
                                   (453,'1_methylpsilocin_present',9,5,5,44,now(),now() ),
                                   (454,'1_methylpsilocin_quantity',9,5,5,44,now(),now() ),
                                   (455,'4_chloroindole_3_acetic_acid_4_CI_IAA_present',9,5,5,44,now(),now() ),
                                   (456,'4_chloroindole_3_acetic_acid_4_CI_IAA_quantity',9,5,5,44,now(),now() ),
                                   (457,'4_hydroxytryptophan_present',9,5,5,44,now(),now() ),
                                   (458,'4_hydroxytryptophan_quantity',9,5,5,44,now(),now() ),
                                   (459,'4_hydroxytryptamine_present',9,5,5,44,now(),now() ),
                                   (460,'4_hydroxytryptamine_quantity',9,5,5,44,now(),now() ),
                                   (461,'4_hydroxy_l_tryptophan_present',9,5,5,44,now(),now() ),
                                   (462,'4_hydroxy_l_tryptophan_quantity',9,5,5,44,now(),now() ),
                                   (463,'4_hydroxyindole_present',9,5,5,44,now(),now() ),
                                   (464,'4_hydroxyindole_quantity',9,5,5,44,now(),now() ),
                                   (465,'4_ho_met_present',9,5,5,44,now(),now() ),
                                   (466,'4_ho_met_quantity',9,5,5,44,now(),now() ),
                                   (467,'4_ho_mipt_present',9,5,5,44,now(),now() ),
                                   (468,'4_ho_mipt_quantity',9,5,5,44,now(),now() ),
                                   (469,'5_hydroxyindoleacetic_acid_present',9,5,5,44,now(),now() ),
                                   (470,'5_hydroxyindoleacetic_acid_quantity',9,5,5,44,now(),now() ),
                                   (471,'5_hydroxytryptamine_present',9,5,5,44,now(),now() ),
                                   (472,'5_hydroxytryptamine_quantity',9,5,5,44,now(),now() ),
                                   (473,'5_hydroxytryptophan_present',9,5,5,44,now(),now() ),
                                   (474,'5_hydroxytryptophan_quantity',9,5,5,44,now(),now() ),
                                   (475,'5_6_dihydroxyindole_dhi_present',9,5,5,44,now(),now() ),
                                   (476,'5_6_dihydroxyindole_dhi_quantity',9,5,5,44,now(),now() ),
                                   (477,'7_acetyl_4_methy_lazulene_1_carbalehyde_present',9,5,5,44,now(),now() ),
                                   (478,'7_acetyl_4_methy_lazulene_1_carbaldehyde_quantity',9,5,5,44,now(),now() ),
                                   (479,'7_isopropenyl_4_methyl_azulene_1_carboxyli_acid_present',9,5,5,44,now(),now() ),
                                   (480,'7_isopropenyl_4_methyl_azulene_1_carboxylic_acid_quantity',9,5,5,44,now(),now() ),
                                   (481,'methyl_stearate_present',9,5,5,44,now(),now() ),
                                   (482,'methyl_stearate_quantity',9,5,5,44,now(),now() ),
                                   (483,'15_hydroxy_3_6_dihydrolactarazulene_present',9,5,5,44,now(),now() ),
                                   (484,'15_hydroxy_3_6_dihydrolactarazulene_quantity',9,5,5,44,now(),now() ),
                                   (485,'15_hydroxy_6_7_dihydrolactarazulene_present',9,5,5,44,now(),now() ),
                                   (486,'15_hydroxy_6_7_dihydrolactarazulene_quantity',9,5,5,44,now(),now() ),
                                   (487,'amatoxins_present',9,5,5,44,now(),now() ),
                                   (488,'amatoxins_quantity',9,5,5,44,now(),now() ),
                                   (489,'amanitins_present',9,5,5,44,now(),now() ),
                                   (490,'amanitins_quantity',9,5,5,44,now(),now() ),
                                   (491,'azulene_present',9,5,5,44,now(),now() ),
                                   (492,'azulene_quantity',9,5,5,44,now(),now() ),
                                   (493,'b-carbolines_present',9,5,5,44,now(),now() ),
                                   (494,'b-carbolines_quantity',9,5,5,44,now(),now() ),
                                   (495,'baeocystin_1_present',9,5,5,44,now(),now() ),
                                   (496,'baeocystin_1_quantity',9,5,5,44,now(),now() ),
                                   (497,'bis_trimethyl_silyl_psilocybin_present',9,5,5,44,now(),now() ),
                                   (498,'bis_trimethyl_silyl_psilocybin_quantity',9,5,5,44,now(),now() ),
                                   (499,'bis_trimethyl_silyl_psilocin_present',9,5,5,44,now(),now() ),
                                   (500,'bis_trimethyl_silyl_psilocin_quantity',9,5,5,44,now(),now() ),
                                   (501,'bufotenin_present',9,5,5,44,now(),now() ),
                                   (502,'bufotenin_quantity',9,5,5,44,now(),now() ),
                                   (503,'bufotenidine_present',9,5,5,44,now(),now() ),
                                   (504,'bufotenidine_quantity',9,5,5,44,now(),now() ),
                                   (505,'cathinone_present',9,5,5,44,now(),now() ),
                                   (506,'cathinone_quantity',9,5,5,44,now(),now() ),
                                   (507,'chamazulene_present',9,5,5,44,now(),now() ),
                                   (508,'chamazulene_quantity',9,5,5,44,now(),now() ),
                                   (509,'d_lysergic_acid_present',9,5,5,44,now(),now() ),
                                   (510,'d-lysergic_acid_quantity',9,5,5,44,now(),now() ),
                                   (511,'dopa_present',9,5,5,44,now(),now() ),
                                   (512,'dopa_quantity',9,5,5,44,now(),now() ),
                                   (513,'dopamine_present',9,5,5,44,now(),now() ),
                                   (514,'dopamine_quantity',9,5,5,44,now(),now() ),
                                   (515,'dopaminechrome_present',9,5,5,44,now(),now() ),
                                   (516,'dopaminechrome_quantity',9,5,5,44,now(),now() ),
                                   (517,'dopamine_quinone_present',9,5,5,44,now(),now() ),
                                   (518,'dopamine_quinone_quantity',9,5,5,44,now(),now() ),
                                   (519,'guaiazulene_present',9,5,5,44,now(),now() ),
                                   (520,'guaiazulene_quantity',9,5,5,44,now(),now() ),
                                   (521,'gyrocyanin_present',9,5,5,44,now(),now() ),
                                   (522,'gyrocyanin_quantity',9,5,5,44,now(),now() ),
                                   (523,'harmane_present',9,5,5,44,now(),now() ),
                                   (524,'harmane_quantity',9,5,5,44,now(),now() ),
                                   (525,'harmine_present',9,5,5,44,now(),now() ),
                                   (526,'harmine_quantity',9,5,5,44,now(),now() ),
                                   (527,'harmol_present',9,5,5,44,now(),now() ),
                                   (528,'harmol_quantity',9,5,5,44,now(),now() ),
                                   (529,'hispidin_present',9,5,5,44,now(),now() ),
                                   (530,'hispidin_quantity',9,5,5,44,now(),now() ),
                                   (531,'indigoidine_present',9,5,5,44,now(),now() ),
                                   (532,'indigoidine_quantity',9,5,5,44,now(),now() ),
                                   (533,'indole_present',9,5,5,44,now(),now() ),
                                   (534,'indole_quantity',9,5,5,44,now(),now() ),
                                   (535,'indole_3_acetic_acid_present',9,5,5,44,now(),now() ),
                                   (536,'indole_3_acetic_acid_quantity',9,5,5,44,now(),now() ),
                                   (537,'indole_3_butyric_acid_present',9,5,5,44,now(),now() ),
                                   (538,'indole_3_butyric_acid_quantity',9,5,5,44,now(),now() ),
                                   (539,'indolyl_present',9,5,5,44,now(),now() ),
                                   (540,'indolyl_quantity',9,5,5,44,now(),now() ),
                                   (541,'isatin_present',9,5,5,44,now(),now() ),
                                   (542,'isatin_quantity',9,5,5,44,now(),now() ),
                                   (543,'leucochrome_present',9,5,5,44,now(),now() ),
                                   (544,'leucochrome_quantity',9,5,5,44,now(),now() ),
                                   (545,'luciferin_present',9,5,5,44,now(),now() ),
                                   (546,'luciferin_quantity',9,5,5,44,now(),now() ),
                                   (547,'luciferase_present',9,5,5,44,now(),now() ),
                                   (548,'luciferase_quantity',9,5,5,44,now(),now() ),
                                   (549,'matricin_present',9,5,5,44,now(),now() ),
                                   (550,'matricin_quantity',9,5,5,44,now(),now() ),
                                   (551,'melatonin_present',9,5,5,44,now(),now() ),
                                   (552,'melatonin_quantity',9,5,5,44,now(),now() ),
                                   (553,'monoamine_oxidase_inhibitors_present',9,5,5,44,now(),now() ),
                                   (554,'monoamine_oxidase_inhibitors_quantity',9,5,5,44,now(),now() ),
                                   (555,'muscarine_present',9,5,5,44,now(),now() ),
                                   (556,'muscarine_quantity',9,5,5,44,now(),now() ),
                                   (557,'n_methyltryptamine_present',9,5,5,44,now(),now() ),
                                   (558,'n_methyltryptamine_quantity',9,5,5,44,now(),now() ),
                                   (559,'n_n_dimethyltryptamine_present',9,5,5,44,now(),now() ),
                                   (560,'n_n_dimethyltryptamine_quantity',9,5,5,44,now(),now() ),
                                   (561,'n_acetylserotonin _nas_normelatonin_present',9,5,5,44,now(),now() ),
                                   (562,'n_acetylserotonin _nas_normelatonin_quantity',9,5,5,44,now(),now() ),
                                   (563,'nitric_oxide_present',9,5,5,44,now(),now() ),
                                   (564,'nitric_oxide_quantity',9,5,5,44,now(),now() ),
                                   (565,'norepinephrine_present',9,5,5,44,now(),now() ),
                                   (566,'norepinephrine_quantity',9,5,5,44,now(),now() ),
                                   (567,'norharmine_present',9,5,5,44,now(),now() ),
                                   (568,'norharmine_quantity',9,5,5,44,now(),now() ),
                                   (569,'norpsilocin_present',9,5,5,44,now(),now() ),
                                   (570,'norpsilocin_quantity',9,5,5,44,now(),now() ),
                                   (571,'oxindole_2_Indolone_present',9,5,5,44,now(),now() ),
                                   (572,'oxindole_2_Indolone_quantity',9,5,5,44,now(),now() ),
                                   (573,'oxytocin_present',9,5,5,44,now(),now() ),
                                   (574,'oxytocin_quantity',9,5,5,44,now(),now() ),
                                   (575,'phallotoxins_and_phalloidins_present',9,5,5,44,now(),now() ),
                                   (576,'phallotoxins_and_phalloidins_quantity',9,5,5,44,now(),now() ),
                                   (577,'phenylethylamine_present',9,5,5,44,now(),now() ),
                                   (578,'phenylethylamine_quantity',9,5,5,44,now(),now() ),
                                   (579,'prolactin_present',9,5,5,44,now(),now() ),
                                   (580,'prolactin_quantity',9,5,5,44,now(),now() ),
                                   (581,'psilacetin_o_acetylpsilocin_4_aco_dmt_present',9,5,5,44,now(),now() ),
                                   (582,'psilacetin (o_acetylpsilocin_4_aco_dmt_quantity',9,5,5,44,now(),now() ),
                                   (583,'psilocybin_1_present',9,5,5,44,now(),now() ),
                                   (584,'psilocybin_1_quantity',9,5,5,44,now(),now() ),
                                   (585,'pulvinic_acids_present',9,5,5,44,now(),now() ),
                                   (586,'pulvinic_acids_quantity',9,5,5,44,now(),now() ),
                                   (587,'quinone_methide_present',9,5,5,44,now(),now() ),
                                   (588,'quinone_methide_quantity',9,5,5,44,now(),now() ),
                                   (589,'sanguinone_a_present',9,5,5,44,now(),now() ),
                                   (590,'sanguinone_a_quantity',9,5,5,44,now(),now() ),
                                   (591,'sanguinone_b_present',9,5,5,44,now(),now() ),
                                   (592,'sanguinone_b_quantity',9,5,5,44,now(),now() ),
                                   (593,'seratoni_5_ht_present',9,5,5,44,now(),now() ),
                                   (594,'seratoni_5_ht_quantity',9,5,5,44,now(),now() ),
                                   (595,'tryptamine_present',9,5,5,44,now(),now() ),
                                   (596,'tryptamine_quantity',9,5,5,44,now(),now() ),
                                   (597,'tryptophan_variegatic_acid present',9,5,5,44,now(),now() ),
                                   (598,'tryptophan_variegatic_acid_quantity',9,5,5,44,now(),now() ),
                                   (599,'vasopressin_present',9,5,5,44,now(),now() ),
                                   (600,'vasopressin_quantity',9,5,5,44,now(),now() ),
                                   (601,'known_novel_maois_monoamine_oxidase_inhibitors_present',9,5,5,44,now(),now() ),
                                   (602,'muscarine_present_2',9,5,5,44,now(),now() ),
                                   (603,'muscimol_present',9,5,5,44,now(),now() ),
                                   (604,'ibotenic_acid_present',9,5,5,44,now(),now() ),
                                   (605,'antamanide_present',9,5,5,44,now(),now() ),
                                   (606,'novel_amatoxins_present',9,5,5,44,now(),now() ),
                                   (607,'phallotoxins_present',9,5,5,44,now(),now() ),
                                   (608,'phallolysin_present',9,5,5,44,now(),now() ),
                                   (609,'virotoxins_present',9,5,5,44,now(),now() ),
                                   (610,'alpha_amanitin_present',9,5,5,44,now(),now() ),
                                   (611,'beta_amanitin_present',9,5,5,44,now(),now() ),
                                   (612,'gamma_amanitin_present',9,5,5,44,now(),now() ),
                                   (613,'epilson_amanitin_present',9,5,5,44,now(),now() ),
                                   (614,'delta_amanitin_present',9,5,5,44,now(),now() ),
                                   (615,'amanullin_present',9,5,5,44,now(),now() ),
                                   (616,'amanullinic_acid_present',9,5,5,44,now(),now() ),
                                   (617,'amaninamide_present',9,5,5,44,now(),now() ),
                                   (618,'amanin_present',9,5,5,44,now(),now() ),
                                   (619,'proamanullin_present',9,5,5,44,now(),now() ),
                                   (620,'anti_bacterial_chemical_present',9,5,5,44,now(),now() ),
                                   (621,'anti_fungal_chemical_present',9,5,5,44,now(),now() ),
                                   (622,'anti_cancer_chemical_present',9,5,5,44,now(),now() ),
                                   (623,'anti_mosquito_chemical_present',9,5,5,44,now(),now() ),
                                   (624,'anti_nematode_chemical_present',9,5,5,44,now(),now() ),
                                   (625,'anti_tick_chemical_present',9,5,5,44,now(),now() ),
                                   (626,'anti_protozoal_chemical_present',9,5,5,44,now(),now() ),
                                   (627,'anti_viral_chemical_present',9,5,5,44,now(),now() ),
                                   (628,'dna_sequence_relevant_production',9,5,5,44,now(),now() ),
                                   (629,'separate_test_caps',9,5,5,44,now(),now() ),
                                   (630,'separate_test_stems',9,5,5,44,now(),now() ),
                                   (631,'separate_test_lamellae_tissue',9,5,5,44,now(),now() ),
                                   (632,'separate_test_mycelium',9,5,5,44,now(),now() ),
                                   (633,'mating_compatibility_agar',2,6,5,44,now(),now() ),
                                   (634,'mating_compatibility_mating_type_locus_sequence',2,6,5,44,now(),now() ),
                                   (635,'mating_compatibility_mating_types_quantity',2,6,5,44,now(),now() ),
                                   (636,'mating_compatibility_mycelium_growth_pattern_description',2,6,5,44,now(),now() ),
                                   (637,'mating_compatibility_mycorrhizal_relationship',2,6,5,44,now(),now() ),
                                   (638,'mating_compatibility_predictive_dna_sequences',2,6,5,44,now(),now() ),
                                   (639,'mycelium_thin_or_thick_walled_hypha_present',7,7,5,44,now(),now() ),
                                   (640,'mycelium_mycelial_cystidia_present',7,7,5,44,now(),now() ),
                                   (641,'mycelium_aerial_hyphae_present',7,7,5,44,now(),now() ),
                                   (642,'mycelium_vegetative_hypha_present',7,7,5,44,now(),now() ),
                                   (643,'mycelium_advancing_zone_present',7,7,5,44,now(),now() ),
                                   (644,'mycelium_conidia_present',7,7,5,44,now(),now() ),
                                   (645,'mycelium_chlamydospores_present',7,7,5,44,now(),now() ),
                                   (646,'mycelium_arthrospores_present',7,7,5,44,now(),now() ),
                                   (647,'mycelium_clamp_connections_present',7,7,5,44,now(),now() ),
                                   (648,'mycelium_anastomoses_present',7,7,5,44,now(),now() ),
                                   (649,'mycelium_shape_form',7,7,5,44,now(),now() ),
                                   (650,'mycelium_size',7,7,5,44,now(),now() ),
                                   (651,'mycelium_elevation_side_view',7,7,5,44,now(),now() ),
                                   (652,'mycelium_margin_border',7,7,5,44,now(),now() ),
                                   (653,'mycelium_surface',7,7,5,44,now(),now() ),
                                   (654,'mycelium_opacity',7,7,5,44,now(),now() ),
                                   (655,'mycelium_colors',7,7,5,44,now(),now() ),
                                   (656,'mycelium_observable_transformations_phases',7,7,5,44,now(),now() ),
                                   (657,'mycelium_reaction_to_sectioning_damage',7,7,5,44,now(),now() ),
                                   (658,'mycelium_cold_shocking_response',7,7,5,44,now(),now() ),
                                   (659,'mycelium_hypha_exhibit_gravitropism',7,7,5,44,now(),now() ),
                                   (660,'mycelium_hypha_exhibit_thigmotropism',7,7,5,44,now(),now() ),
                                   (661,'mycelium_hypha_exhibit_phototropism',7,7,5,44,now(),now() ),
                                   (662,'mycelium_hypha_exhibit_aerotropism',7,7,5,44,now(),now() ),
                                   (663,'mycelium_hypha_exhibit_galvanotropism',7,7,5,44,now(),now() ),
                                   (664,'mycelium_hyphal_coils_present',7,7,5,44,now(),now() ),
                                   (665,'mycelium_electromagnetic_light_test',7,7,5,44,now(),now() ),
                                   (666,'mycelium_zonate_mycelium',7,7,5,44,now(),now() ),
                                   (667,'dna_complete_its_region_sequence',7,8,5,44,now(),now() ),
                                   (668,'dna_entire_genome_sequence',7,8,5,44,now(),now() ),
                                   (669,'dna_exome_sequencing',7,8,5,44,now(),now() ),
                                   (670,'dna_additional_regions',7,8,5,44,now(),now() ),
                                   (671,'dna_genome_sequence_sub_surface_mycelium',7,8,5,44,now(),now() ),
                                   (672,'dna_substrata_sequences',7,8,5,44,now(),now() ),
                                   (673,'dna_all_sequences',7,8,5,44,now(),now() );

