INSERT INTO `mr_characters` VALUES (1,'id',1,1,23, 1,now(), now() ),
                                   (2, 'abundance', 9, 1, 16,  1,now(), now() ),
                                   (3,'mushroom_age',9,1,16, 1, now(), now() ),
                                   (4,'odor',8,1,16, 1, now(), now() ),
                                   (5,'taste',7,1,16, 1, now(), now() ),
                                   (6,'toxic',9,1,16, 1, now(), now() ),
                                   (7,'habit',9,1,11, 1, now(), now() ),
                                   (8,'pileus_width',2,1,3, 1, now(), now() ),
                                   (9,'pileus_height',2,1,3, 1, now(), now() ),
                                   (10,'pileus_shape',9,1,3, 1, now(), now() ),
                                   (11,'pileus_shape_top_views',9,1,3, 1, now(), now() ),
                                   (12,'pileus_color',6,1,3, 1, now(), now() ),
                                   (13,'pileus_color_disc',6,1,3, 1, now(), now() ),
                                   (14,'pileus_color_margin',6,1,3, 1, now(), now() ),
                                   (15,'pileus_color_background',6,1,3, 1, now(), now() ),
                                   (16,'pileus_color_fibrils',6,1,3, 1, now(), now() ),
                                   (17,'pileus_color_bruised',6,1,3, 1, now(), now() ),
                                   (18,'pileus_color_wet',6,1,3, 1, now(), now() ),
                                   (19,'pileus_color_dry',6,1,3, 1, now(), now() ),
                                   (20,'pileus_surface_dryness',9,1,3, 1, now(), now() ),
                                   (21,'pileus_surface_texture',13,1,3, 1, now(), now() ),
                                   (22,'pileus_margin_shape',9,1,3, 1, now(), now() ),
                                   (23,'pileus_margin_type',9,1,3, 1, now(), now() ),
                                   (24,'pileus_hairy_y_n',14,1,3, 1, now(), now() ),
                                   (25,'pileus_context_flesh_color_moist',6,1,3, 1, now(), now() ),
                                   (26,'pileus_context_flesh_color_dry',6,1,3, 1, now(), now() ),
                                   (27,'pileus_context_flesh_color_cuticle',6,1,3, 1, now(), now() ),
                                   (28,'pileus_context_flesh_thickness_disc',2,1,3, 1, now(), now() ),
                                   (29,'pileus_context_flesh_thickness_margin',2,1,3, 1, now(), now() ),
                                   (30,'pileus_context_flesh_texture',13,1,3, 1, now(), now() ),
                                   (31,'pileus_context_flesh_latex_color',6,1,3, 1, now(), now() ),
                                   (32,'pileus_context_flesh_latex_color_exposed',6,1,3, 1, now(), now() ),
                                   (33,'pileus_context_flesh_latex_taste',7,1,3, 1, now(), now() ),
                                   (34,'pileus_context_flesh_latex_abundance',15,1,3, 1, now(), now() ),
                                   (35,'lamella_attachment',9,1,4, 1, now(), now() ),
                                   (36,'lamella_breadth',2,1,4, 1, now(), now() ),
                                   (37,'lamella_thickness',2,1,4, 1, now(), now() ),
                                   (38,'lamella_spacing',9,1,4, 1, now(), now() ),
                                   (39,'lamella_color_young',6,1,4, 1, now(), now() ),
                                   (40,'lamella_color_mature',6,1,4, 1, now(), now() ),
                                   (41,'lamella_edge',9,1,4, 1, now(), now() ),
                                   (42,'lamella_misc_waxy_y_n',14,1,4, 1, now(), now() ),
                                   (43,'lamella_misc_arid_dry_y_n',14,1,4, 1, now(), now() ),
                                   (44,'lamella_misc_deliquescent_y_n',14,1,4, 1, now(), now() ),
                                   (45,'stipe_location',9,1,5, 1, now(), now() ),
                                   (46,'stipe_height',2,1,5, 1, now(), now() ),
                                   (47,'stipe_diameter_top',2,1,5, 1, now(), now() ),
                                   (48,'stipe_diameter_mid',2,1,5, 1, now(), now() ),
                                   (49,'stipe_diameter_low',2,1,5, 1, now(), now() ),
                                   (50,'stipe_shape',9,1,5, 1, now(), now() ),
                                   (51,'stipe_color',6,1,5, 1, now(), now() ),
                                   (52,'stipe_color_change',6,1,5, 1, now(), now() ),
                                   (53,'stipe_color_base',6,1,5, 1, now(), now() ),
                                   (54,'stipe_color_apex',6,1,5, 1, now(), now() ),
                                   (55,'stipe_color_interior',6,1,5, 1, now(), now() ),
                                   (56,'stipe_color_exterior',6,1,5, 1, now(), now() ),
                                   (57,'stipe_color_bruise',6,1,5, 1, now(), now() ),
                                   (58,'stipe_surface',9,1,5, 1, now(), now() ),
                                   (59,'stipe_texture',13,1,5, 1, now(), now() ),
                                   (60,'stipe_interior',9,1,5, 1, now(), now() ),
                                   (61,'partial_inner_veil_annular_ring_position',9,1,6, 1, now(), now() ),
                                   (62,'veil_annulus',4,1,6, 1, now(), now() ),
                                   (63,'partial_inner_veil_color',6,1,6, 1, now(), now() ),
                                   (64,'partial_inner_veil_texture',13,1,6, 1, now(), now() ),
                                   (65,'partial_inner_veil_fate',9,1,6, 1, now(), now() ),
                                   (66,'partial_inner_veil_annular_ring',4,1,6, 1, now(), now() ),
                                   (67,'partial_inner_veil_appearance',9,1,6, 1, now(), now() ),
                                   (68,'universal_outer_veil_description',4,1,6, 1, now(), now() ),
                                   (69,'universal_outer_veil_volva',4,1,6, 1, now(), now() ),
                                   (70,'bulb_type',9,1,6, 1, now(), now() ),
                                   (71,'mycelium_color',6,1,7, 1, now(), now() ),
                                   (72,'mycelium_texture',13,1,7, 1, now(), now() ),
                                   (73,'spore_color',6,1,8, 1, now(), now() ),
                                   (74,'spore_range_low',3,1,8, 1, now(), now() ),
                                   (75,'spore_range_high',3,1,8, 1, now(), now() ),
                                   (76,'habitat',9,1,11, 1, now(), now() ),
                                   (77,'soil_type',9,1,11, 1, now(), now() ),
                                   (78,'soil_temp',4,1,11, 1, now(), now() ),
                                   (79,'air_temp',4,1,11, 1, now(), now() ),
                                   (80,'plant_association',9,1,11, 1, now(), now() ),
                                   (81,'rhizomorph_color',6,1,12, 1, now(), now() ),
                                   (82,'rhizomorph_texture',13,1,12, 1, now(), now() ),
                                   (83,'chem_reaction',9,1,13, 1, now(), now() ),
                                   (84,'weight_before_dry',4,1,17, 1, now(), now() ),
                                   (85,'weight_after_dry',4,1,17, 1, now(), now() ),
                                   (86,'elevation',4,1,11, 1, now(), now() ),
                                   (87,'soil_ph',4,1,11, 1, now(), now() ),
                                   (88,'stipe_latex_color_exposed',6,1,5, 1, now(), now() ),
                                   (89,'stipe_latex_taste',7,1,5, 1, now(), now() ),
                                   (90,'stipe_latex_abundance',15,1,5, 1, now(), now() ),
                                   (91,'mycobank_name',5,1,16, 1, now(), now() ),
                                   (92,'inaturalist_num',5,1,16, 1, now(), now() ),
                                   (93,'mushroom_observer_num',5,1,16, 1, now(), now() ),
                                   (94,'location_found_latitude',5,1,15, 1, now(), now() ),
                                   (95,'location_found_longitude',5,1,15, 1, now(), now() ),
                                   (96,'project_belong_to',9,1,16, 1, now(), now() ),
                                   (97,'microscope_slides_included',14,1,17, 1, now(), now() ),
                                   (98,'preservation_method',9,1,17, 1, now(), now() ),
                                   (99,'annulus_position',9,9,6,1, now(), now() ),
                                   (100,'mushroom_storage_location',9,1,17, 1, now(), now() ),
                                   (101,'countries',9,1,15, 1, now(), now() ),
                                   (102,'display_options',9,1,15, 1, now(), now()),
                                   (103,'parts',9,1,15, 1, now(), now()),
                                   (104,'source_data_types',9,1,15, 1, now(), now()),
                                   (105,'fungus_types',9,1,15, 1, now(), now()),
                                   (106,'universal_outer_veil_appearances',9,1,15, 1, now(), now()),
                                   (107,'universal_outer_veil_fates',9,1,15, 1, now(), now()),
                                   (108,'universal_outer_veil_textures',9,1,15, 1, now(), now()),
                                   (109,'veils',9,1,15, 1, now(), now()),
                                   (110,'synonyms',9,1,15, 1, now(), now());

