<?php

use App\Http\Controllers\AbundanceController;
use App\Http\Controllers\AnnulusPositionController;
use App\Http\Controllers\BulbTypeController;
use App\Http\Controllers\CapContextFleshController;
use App\Http\Controllers\CapMarginShapeController;
use App\Http\Controllers\CapMarginTypeController;
use App\Http\Controllers\CapShapeController;
use App\Http\Controllers\CapShapeTopController;
use App\Http\Controllers\CapSurfaceDrynessController;
use App\Http\Controllers\CapSurfaceTextureController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\ChemReactionController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\DataImageSourceController;
use App\Http\Controllers\DataSourceController;
use App\Http\Controllers\DataSourceDataTypeController;
use App\Http\Controllers\DisplayOptionController;
use App\Http\Controllers\DnaSequenceController;
use App\Http\Controllers\EpithetController;
use App\Http\Controllers\FungusTypeController;
use App\Http\Controllers\GenusController;
use App\Http\Controllers\GillAttachmentController;
use App\Http\Controllers\GillBreadthController;
use App\Http\Controllers\GillContextFleshLatexAbundanceController;
use App\Http\Controllers\GillEdgeController;
use App\Http\Controllers\GillOtherController;
use App\Http\Controllers\GillSpacingController;
use App\Http\Controllers\GillThicknessController;
use App\Http\Controllers\HabitatController;
use App\Http\Controllers\HabitController;
use App\Http\Controllers\ImageSpecimenController;
use App\Http\Controllers\LensController;
use App\Http\Controllers\MemberListClusterController;
use App\Http\Controllers\MemberListGroupController;
use App\Http\Controllers\MemberTypeController;
use App\Http\Controllers\OdorController;
use App\Http\Controllers\PartController;
use App\Http\Controllers\PartialInnerVeilAnnulusRingPositionController;
use App\Http\Controllers\PartialInnerVeilAppearanceController;
use App\Http\Controllers\PartialInnerVeilFateController;
use App\Http\Controllers\PartialInnerVeilTextureController;
use App\Http\Controllers\PlantAssociationController;
use App\Http\Controllers\PlantController;
use App\Http\Controllers\PossibleMatchController;
use App\Http\Controllers\PreservationMethodController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SoilTypeController;
use App\Http\Controllers\SpeciesController;
use App\Http\Controllers\SpecimenAgeController;
use App\Http\Controllers\SpecimenClusterController;
use App\Http\Controllers\SpecimenController;
use App\Http\Controllers\SpecimenGroupController;
use App\Http\Controllers\SpecimenLocationNowController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\StemInteriorController;
use App\Http\Controllers\StemLocationController;
use App\Http\Controllers\StemShapeController;
use App\Http\Controllers\StemSurfaceController;
use App\Http\Controllers\StemTextureController;
use App\Http\Controllers\SynonymController;
use App\Http\Controllers\TasteController;
use App\Http\Controllers\ToxicController;
use App\Http\Controllers\TreeController;
use App\Http\Controllers\UniversalOuterVeilAppearanceController;
use App\Http\Controllers\UniversalOuterVeilFateController;
use App\Http\Controllers\UniversalOuterVeilTextureController;
use App\Http\Controllers\VeilController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'home')->name('home');
Route::view('/contact', 'contact')->name('contact');
Route::view('/about', 'about')->name('about');
Route::view('/books', 'books')->name('books');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('specimens', SpecimenController::class);
    Route::resource('characters', CharacterController::class);

    Route::resource('look_up_tables.abundance', AbundanceController::class);
    Route::resource('look_up_tables.annulus_position', AnnulusPositionController::class);
    Route::resource('look_up_tables.bulb_type', BulbTypeController::class);
    Route::resource('look_up_tables.cap_context_flesh', CapContextFleshController::class);
    Route::resource('look_up_tables.cap_margin_shape', CapMarginShapeController::class);
    Route::resource('look_up_tables.cap_margin_type', CapMarginTypeController::class);
    Route::resource('look_up_tables.cap_shape', CapShapeController::class);
    Route::resource('look_up_tables.cap_shape_top', CapShapeTopController::class);
    Route::resource('look_up_tables.cap_surface_dryness', CapSurfaceDrynessController::class);
    Route::resource('look_up_tables.cap_surface_texture', CapSurfaceTextureController::class);
    Route::resource('look_up_tables.chem_reaction', ChemReactionController::class);
    Route::resource('look_up_tables.country', CountryController::class);
    Route::resource('look_up_tables.data_image_source', DataImageSourceController::class);
    Route::resource('look_up_tables.data_source', DataSourceController::class);
    Route::resource('look_up_tables.data_source_data_type', DataSourceDataTypeController::class);
    Route::resource('look_up_tables.display_option', DisplayOptionController::class);
    Route::resource('look_up_tables.dna_sequence', DnaSequenceController::class);
    Route::resource('look_up_tables.epithet', EpithetController::class);
    Route::resource('look_up_tables.fungus_type', FungusTypeController::class);
    Route::resource('look_up_tables.genus', GenusController::class);
    Route::resource('look_up_tables.gill_attachment', GillAttachmentController::class);
    Route::resource('look_up_tables.gill_breadth', GillBreadthController::class);
    Route::resource('look_up_tables.gill_context_flesh_latex_abundance', GillContextFleshLatexAbundanceController::class);
    Route::resource('look_up_tables.gill_edge', GillEdgeController::class);
    Route::resource('look_up_tables.gill_other', GillOtherController::class);
    Route::resource('look_up_tables.gill_spacing', GillSpacingController::class);
    Route::resource('look_up_tables.gill_thickness', GillThicknessController::class);
    Route::resource('look_up_tables.habitat', HabitatController::class);
    Route::resource('look_up_tables.habit', HabitController::class);
    Route::resource('look_up_tables.image_specimen', ImageSpecimenController::class);
    Route::resource('look_up_tables.lens', LensController::class);
    Route::resource('look_up_tables.member_list_cluster', MemberListClusterController::class);
    Route::resource('look_up_tables.member_list_group', MemberListGroupController::class);
    Route::resource('look_up_tables.member_type', MemberTypeController::class);
    Route::resource('look_up_tables.odor', OdorController::class);
    Route::resource('look_up_tables.part', PartController::class);
    Route::resource('look_up_tables.partial_inner_veil_annulus_ring_position', PartialInnerVeilAnnulusRingPositionController::class);
    Route::resource('look_up_tables.partial_inner_veil_appearance', PartialInnerVeilAppearanceController::class);
    Route::resource('look_up_tables.partial_inner_veil_fate', PartialInnerVeilFateController::class);
    Route::resource('look_up_tables.partial_inner_veil_texture', PartialInnerVeilTextureController::class);
    Route::resource('look_up_tables.plant_association', PlantAssociationController::class);
    Route::resource('look_up_tables.plant', PlantController::class);
    Route::resource('look_up_tables.possible_match', PossibleMatchController::class);
    Route::resource('look_up_tables.preservation_method', PreservationMethodController::class);
    Route::resource('look_up_tables.soil_type', SoilTypeController::class);
    Route::resource('look_up_tables.species', SpeciesController::class);
    Route::resource('look_up_tables.specimen_age', SpecimenAgeController::class);
    Route::resource('look_up_tables.specimen_cluster', SpecimenClusterController::class);
    Route::resource('look_up_tables.specimen_group', SpecimenGroupController::class);
    Route::resource('look_up_tables.specimen_location_now', SpecimenLocationNowController::class);
    Route::resource('look_up_tables.state', StateController::class);
    Route::resource('look_up_tables.stem_interior', StemInteriorController::class);
    Route::resource('look_up_tables.stem_location', StemLocationController::class);
    Route::resource('look_up_tables.stem_shape', StemShapeController::class);
    Route::resource('look_up_tables.stem_surface', StemSurfaceController::class);
    Route::resource('look_up_tables.stem_texture', StemTextureController::class);
    Route::resource('look_up_tables.synonym', SynonymController::class);
    Route::resource('look_up_tables.taste', TasteController::class);
    Route::resource('look_up_tables.toxic', ToxicController::class);
    Route::resource('look_up_tables.tree', TreeController::class);
    Route::resource('look_up_tables.universal_outer_veil_appearance', UniversalOuterVeilAppearanceController::class);
    Route::resource('look_up_tables.universal_outer_veil_fate', UniversalOuterVeilFateController::class);
    Route::resource('look_up_tables.universal_outer_veil_texture', UniversalOuterVeilTextureController::class);
    Route::resource('look_up_tables.veil', VeilController::class);

});

Route::get('phpmyinfo', function () {
    phpinfo();
})->name('phpmyinfo');

require __DIR__.'/auth.php';
