require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/all_group_mushrooms", type: :request do
  let(:source) { create(:source) }

  # This should return the minimal set of attributes required to create a valid
  # AllGroupMushroom. As you add validations to AllGroupMushroom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AllGroupMushroom.create! valid_attributes
      get all_group_mushrooms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      all_group_mushroom = AllGroupMushroom.create! valid_attributes
      get all_group_mushroom_url(all_group_mushroom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_all_group_mushroom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      all_group_mushroom = AllGroupMushroom.create! valid_attributes
      get edit_all_group_mushroom_url(all_group_mushroom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AllGroupMushroom" do
        expect {
          post all_group_mushrooms_url, params: {all_group_mushroom: valid_attributes}
        }.to change(AllGroupMushroom, :count).by(1)
      end

      it "redirects to the created all_group_mushroom" do
        post all_group_mushrooms_url, params: {all_group_mushroom: valid_attributes}
        expect(response).to redirect_to(all_group_mushroom_url(AllGroupMushroom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AllGroupMushroom" do
        expect {
          post all_group_mushrooms_url, params: {all_group_mushroom: invalid_attributes}
        }.to change(AllGroupMushroom, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post all_group_mushrooms_url, params: {all_group_mushroom: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested all_group_mushroom" do
        all_group_mushroom = AllGroupMushroom.create! valid_attributes
        patch all_group_mushroom_url(all_group_mushroom), params: {all_group_mushroom: new_attributes}
        all_group_mushroom.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the all_group_mushroom" do
        all_group_mushroom = AllGroupMushroom.create! valid_attributes
        patch all_group_mushroom_url(all_group_mushroom), params: {all_group_mushroom: new_attributes}
        all_group_mushroom.reload
        expect(response).to redirect_to(all_group_mushroom_url(all_group_mushroom))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        all_group_mushroom = AllGroupMushroom.create! valid_attributes
        patch all_group_mushroom_url(all_group_mushroom), params: {all_group_mushroom: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested all_group_mushroom" do
      all_group_mushroom = AllGroupMushroom.create! valid_attributes
      expect {
        delete all_group_mushroom_url(all_group_mushroom)
      }.to change(AllGroupMushroom, :count).by(-1)
    end

    it "redirects to the all_group_mushrooms list" do
      all_group_mushroom = AllGroupMushroom.create! valid_attributes
      delete all_group_mushroom_url(all_group_mushroom)
      expect(response).to redirect_to(all_group_mushrooms_url)
    end
  end
end
