require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dna_sequences", type: :request do
  let(:source) { create(:source) }

  # This should return the minimal set of attributes required to create a valid
  # DnaSequence. As you add validations to DnaSequence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DnaSequence.create! valid_attributes
      get dna_sequences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dna_sequence = DnaSequence.create! valid_attributes
      get dna_sequence_url(dna_sequence)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dna_sequence_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      dna_sequence = DnaSequence.create! valid_attributes
      get edit_dna_sequence_url(dna_sequence)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DnaSequence" do
        expect {
          post dna_sequences_url, params: {dna_sequence: valid_attributes}
        }.to change(DnaSequence, :count).by(1)
      end

      it "redirects to the created dna_sequence" do
        post dna_sequences_url, params: {dna_sequence: valid_attributes}
        expect(response).to redirect_to(dna_sequence_url(DnaSequence.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DnaSequence" do
        expect {
          post dna_sequences_url, params: {dna_sequence: invalid_attributes}
        }.to change(DnaSequence, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dna_sequences_url, params: {dna_sequence: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dna_sequence" do
        dna_sequence = DnaSequence.create! valid_attributes
        patch dna_sequence_url(dna_sequence), params: {dna_sequence: new_attributes}
        dna_sequence.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dna_sequence" do
        dna_sequence = DnaSequence.create! valid_attributes
        patch dna_sequence_url(dna_sequence), params: {dna_sequence: new_attributes}
        dna_sequence.reload
        expect(response).to redirect_to(dna_sequence_url(dna_sequence))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        dna_sequence = DnaSequence.create! valid_attributes
        patch dna_sequence_url(dna_sequence), params: {dna_sequence: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dna_sequence" do
      dna_sequence = DnaSequence.create! valid_attributes
      expect {
        delete dna_sequence_url(dna_sequence)
      }.to change(DnaSequence, :count).by(-1)
    end

    it "redirects to the dna_sequences list" do
      dna_sequence = DnaSequence.create! valid_attributes
      delete dna_sequence_url(dna_sequence)
      expect(response).to redirect_to(dna_sequences_url)
    end
  end
end
