require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lens", type: :request do
  let(:source) { create(:source) }

  # This should return the minimal set of attributes required to create a valid
  # Lens. As you add validations to Lens, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Lens.create! valid_attributes
      get lens_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lens = Lens.create! valid_attributes
      get lens_url(lens)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lens_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lens = Lens.create! valid_attributes
      get edit_lens_url(lens)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lens" do
        expect {
          post lens_index_url, params: {lens: valid_attributes}
        }.to change(Lens, :count).by(1)
      end

      it "redirects to the created lens" do
        post lens_index_url, params: {lens: valid_attributes}
        expect(response).to redirect_to(lens_url(Lens.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lens" do
        expect {
          post lens_index_url, params: {lens: invalid_attributes}
        }.to change(Lens, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post lens_index_url, params: {lens: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lens" do
        lens = Lens.create! valid_attributes
        patch lens_url(lens), params: {lens: new_attributes}
        lens.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lens" do
        lens = Lens.create! valid_attributes
        patch lens_url(lens), params: {lens: new_attributes}
        lens.reload
        expect(response).to redirect_to(lens_url(lens))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lens = Lens.create! valid_attributes
        patch lens_url(lens), params: {lens: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lens" do
      lens = Lens.create! valid_attributes
      expect {
        delete lens_url(lens)
      }.to change(Lens, :count).by(-1)
    end

    it "redirects to the lens list" do
      lens = Lens.create! valid_attributes
      delete lens_url(lens)
      expect(response).to redirect_to(lens_index_url)
    end
  end
end
