require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mr_character_mushrooms", type: :request do
  let(:source) { create(:source) }

  # This should return the minimal set of attributes required to create a valid
  # MrCharacterMushroom. As you add validations to MrCharacterMushroom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MrCharacterMushroom.create! valid_attributes
      get mr_character_mushrooms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
      get mr_character_mushroom_url(mr_character_mushroom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mr_character_mushroom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
      get edit_mr_character_mushroom_url(mr_character_mushroom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MrCharacterMushroom" do
        expect {
          post mr_character_mushrooms_url, params: {mr_character_mushroom: valid_attributes}
        }.to change(MrCharacterMushroom, :count).by(1)
      end

      it "redirects to the created mr_character_mushroom" do
        post mr_character_mushrooms_url, params: {mr_character_mushroom: valid_attributes}
        expect(response).to redirect_to(mr_character_mushroom_url(MrCharacterMushroom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MrCharacterMushroom" do
        expect {
          post mr_character_mushrooms_url, params: {mr_character_mushroom: invalid_attributes}
        }.to change(MrCharacterMushroom, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mr_character_mushrooms_url, params: {mr_character_mushroom: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mr_character_mushroom" do
        mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
        patch mr_character_mushroom_url(mr_character_mushroom), params: {mr_character_mushroom: new_attributes}
        mr_character_mushroom.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mr_character_mushroom" do
        mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
        patch mr_character_mushroom_url(mr_character_mushroom), params: {mr_character_mushroom: new_attributes}
        mr_character_mushroom.reload
        expect(response).to redirect_to(mr_character_mushroom_url(mr_character_mushroom))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
        patch mr_character_mushroom_url(mr_character_mushroom), params: {mr_character_mushroom: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mr_character_mushroom" do
      mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
      expect {
        delete mr_character_mushroom_url(mr_character_mushroom)
      }.to change(MrCharacterMushroom, :count).by(-1)
    end

    it "redirects to the mr_character_mushrooms list" do
      mr_character_mushroom = MrCharacterMushroom.create! valid_attributes
      delete mr_character_mushroom_url(mr_character_mushroom)
      expect(response).to redirect_to(mr_character_mushrooms_url)
    end
  end
end
