# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/mr_characters', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # MrCharacter. As you add validations to MrCharacter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MrCharacter.create! valid_attributes
      get mr_characters_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      mr_character = MrCharacter.create! valid_attributes
      get mr_character_url(mr_character)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_mr_character_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      mr_character = MrCharacter.create! valid_attributes
      get edit_mr_character_url(mr_character)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MrCharacter' do
        expect do
          post mr_characters_url, params: { mr_character: valid_attributes }
        end.to change(MrCharacter, :count).by(1)
      end

      it 'redirects to the created mr_character' do
        post mr_characters_url, params: { mr_character: valid_attributes }
        expect(response).to redirect_to(mr_character_url(MrCharacter.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MrCharacter' do
        expect do
          post mr_characters_url, params: { mr_character: invalid_attributes }
        end.not_to change(MrCharacter, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mr_characters_url, params: { mr_character: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested mr_character' do
        mr_character = MrCharacter.create! valid_attributes
        patch mr_character_url(mr_character), params: { mr_character: new_attributes }
        mr_character.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the mr_character' do
        mr_character = MrCharacter.create! valid_attributes
        patch mr_character_url(mr_character), params: { mr_character: new_attributes }
        mr_character.reload
        expect(response).to redirect_to(mr_character_url(mr_character))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mr_character = MrCharacter.create! valid_attributes
        patch mr_character_url(mr_character), params: { mr_character: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested mr_character' do
      mr_character = MrCharacter.create! valid_attributes
      expect do
        delete mr_character_url(mr_character)
      end.to change(MrCharacter, :count).by(-1)
    end

    it 'redirects to the mr_characters list' do
      mr_character = MrCharacter.create! valid_attributes
      delete mr_character_url(mr_character)
      expect(response).to redirect_to(mr_characters_url)
    end
  end
end
