require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plant_associations", type: :request do
  let(:source) { create(:source) }

  # This should return the minimal set of attributes required to create a valid
  # PlantAssociation. As you add validations to PlantAssociation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlantAssociation.create! valid_attributes
      get plant_associations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      plant_association = PlantAssociation.create! valid_attributes
      get plant_association_url(plant_association)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_plant_association_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      plant_association = PlantAssociation.create! valid_attributes
      get edit_plant_association_url(plant_association)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlantAssociation" do
        expect {
          post plant_associations_url, params: {plant_association: valid_attributes}
        }.to change(PlantAssociation, :count).by(1)
      end

      it "redirects to the created plant_association" do
        post plant_associations_url, params: {plant_association: valid_attributes}
        expect(response).to redirect_to(plant_association_url(PlantAssociation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlantAssociation" do
        expect {
          post plant_associations_url, params: {plant_association: invalid_attributes}
        }.to change(PlantAssociation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post plant_associations_url, params: {plant_association: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plant_association" do
        plant_association = PlantAssociation.create! valid_attributes
        patch plant_association_url(plant_association), params: {plant_association: new_attributes}
        plant_association.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the plant_association" do
        plant_association = PlantAssociation.create! valid_attributes
        patch plant_association_url(plant_association), params: {plant_association: new_attributes}
        plant_association.reload
        expect(response).to redirect_to(plant_association_url(plant_association))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        plant_association = PlantAssociation.create! valid_attributes
        patch plant_association_url(plant_association), params: {plant_association: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested plant_association" do
      plant_association = PlantAssociation.create! valid_attributes
      expect {
        delete plant_association_url(plant_association)
      }.to change(PlantAssociation, :count).by(-1)
    end

    it "redirects to the plant_associations list" do
      plant_association = PlantAssociation.create! valid_attributes
      delete plant_association_url(plant_association)
      expect(response).to redirect_to(plant_associations_url)
    end
  end
end
