# Name of your application. Used to uniquely configure containers.
service: mrdbid

# Name of the container image.
# Use your Docker Hub repo name without a slash.
image: willmrdbid/willmrdbid-mrdbid  # NOT docker.io/willmrdbid/willmrdbid-mrdbid

# Deploy to these servers.
servers:
  web:
    - 85.31.233.192

proxy:
  ssl: true
  host: mrdbid.com

# Credentials for your image host.
registry:
  server: docker.io
  username: willmrdbid
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - DATABASE_URL
    - SMTP_ADDRESS
    - SMTP_PORT
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_AUTH
    - SMTP_ENABLE_STARTTLS_AUTO
    - MAILER_FROM
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage (e.g., Active Storage).
volumes:
  - "mrdbid_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

# MySQL accessory (private on Docker network; no host port).
accessories:
  mysql:
    image: mysql:8
    host: 85.31.233.192
    env:
      clear:
        MYSQL_DATABASE: mrbid_production
        MYSQL_USER: app
      secret:
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    volumes:
      - /var/lib/mrdbid/mysql:/var/lib/mysql

